# Normalizacion en SQL

### Escenarios e importancia

Escenarios donde se suele utilizar la normalización:

* **Integridad de datos:** Imagina una base de datos que contiene información de clientes. Sin normalización, si un cliente cambia su edad, tendríamos que actualizarla en varios lugares, lo que aumentaría el riesgo de inconsistencias. Al normalizar los datos, podemos tener tablas separadas vinculadas por un identificador único que garantizará que los datos se mantengan precisos y coherentes.
* **Eficiencia en las consultas:** Consideremos una base de datos compleja con múltiples tablas relacionadas que almacena información redundante. En este escenario, las consultas que involucran uniones (*joins*) se vuelven más complicadas y consumen más recursos. La normalización ayudará a simplificar las consultas al dividir los datos en tablas más pequeñas, donde cada tabla contiene solo información relevante, reduciendo así la necesidad de uniones complejas.
* **Optimización del almacenamiento:** Un problema importante con los datos redundantes es que ocupan espacio de almacenamiento innecesario. Por ejemplo, si almacenamos los mismos detalles del producto en cada registro de pedido, se produce una duplicación. Con la normalización, puedes eliminar la redundancia dividiendo los datos en tablas separadas.

¿Por qué es importante la normalización en SQL?:

* **Reduce la redundancia:** La redundancia ocurre cuando la misma información se almacena varias veces; una buena forma de evitarlo es dividiendo los datos en tablas más pequeñas.
* **Mejora el rendimiento de las consultas:** Puedes ejecutar consultas de forma más rápida en tablas pequeñas que han sido sometidas a un proceso de normalización.
* **Minimiza las anomalías de actualización:** Con tablas normalizadas, puedes actualizar los datos fácilmente sin afectar a otros registros.
* **Mejora la integridad de los datos:** Garantiza que la información se mantenga coherente y precisa.

### Niveles de Normalización

**1NF (Primera Forma Normal)**

Este nivel de normalización garantiza que cada columna de tus datos contenga únicamente valores atómicos. En este contexto, valores atómicos significa que cada entrada en una columna es indivisible. Es como decir que cada celda de una hoja de cálculo debe contener solo una pieza de información. La 1NF asegura la atomicidad de los datos, con cada celda de la columna conteniendo un solo valor y cada columna con un nombre único.

**2NF (Segunda Forma Normal)**

La Segunda Forma Normal elimina las dependencias parciales al garantizar que los atributos que no son clave dependan únicamente de la clave primaria. Lo que esto significa, en esencia, es que debe haber una relación directa entre cada columna y la clave primaria, y no entre otras columnas.

**3NF (Tercera Forma Normal)**

La 3NF se basa en la 2NF al eliminar las dependencias transitivas. Una dependencia transitiva ocurre cuando un atributo que no es clave depende de otro atributo que tampoco es clave, el cual a su vez depende de la clave primaria. Básicamente, toma su significado de la ley transitiva.

Fuente: https://www.datacamp.com/tutorial/normalization-in-sql

### Otras mejoras de diseño

Creación de tablas de referencia (lookup tables o reference tables), con base en los siguientes beneficios hipotéticos:

*   Optimización de Almacenamiento: la sustitución de texto repetitivo por un código numérico más ligero permite la reducción de espacio en disco, incrementa la velocidad de indexación y permite mayor agilidad en el filtrado.
*   Garantía de Integridad Referencial: Evitas que alguien escriba "Venta" en lugar de "Ventas" por error.
*   Gestión del Dominio de Datos. Al codificar los valores de cada categoría, se define formalmente el dominio del atributo en cuestión. Mediante una clave foránea, se puede forzar la integridad referencial, incrementando la consistencia de datos.
*   Flexibilidad. La utilización de tablas de referencia permite realizar modificaciones sobre los valores de las tablas de referencia, sin realizar modificaciones sobre las tablas de transacciones.

Sources: https://www.datacamp.com/es/tutorial/normalization-in-dbms

# Aspectos preliminares

In [2]:
# Importacion de librerias.
import pandas as pd
import numpy as np
import re
import os, sys, zipfile, shutil
from pandasql import sqldf

In [3]:
# Evaluacion del current directory y environment.
print(os.getcwd())
print(sys.executable)

d:\Github\data-architectures\01_data_normalization\notebooks
d:\Github\data-architectures\.venv\Scripts\python.exe

In [ ]:
# Directorio de datos.
data_path = '../../data/raw/'
output_dir = '../../db_input/'

# Application_test

### Analisis de datos preliminar

In [5]:
# Lectura del dataset.
csv_name = 'application_test.csv'
df = pd.read_csv(data_path + csv_name)

# Head del dataset.
df.info()

# Head del dataset.
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Columns: 121 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(40), object(16)
memory usage: 45.0+ MB

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Obtención de valores únicos para atributos categóricos y numéricos no float.
for column in df.columns:
    unique_values = df[column].unique()

    # Indicador para verificar si la columna contiene algún valor float no entero (excluyendo NaN)
    contains_non_integer_float = False

    # Iterar sobre los valores únicos para encontrar floats no enteros
    for val in unique_values:
        # Verificar si el valor es un float y no es NaN
        if isinstance(val, float) and not np.isnan(val):
            # Verificar si el float tiene una parte decimal distinta de cero
            if val != int(val):
                contains_non_integer_float = True
                break  # Se encontró un float no entero, no es necesario seguir verificando

    # Si no se encontró ningún float no entero, imprimir los valores únicos de la columna
    if not contains_non_integer_float:
        print(f"Columna '{column}':{unique_values}")

Columna 'SK_ID_CURR':[100001 100005 100013 ... 456223 456224 456250]
Columna 'NAME_CONTRACT_TYPE':['Cash loans' 'Revolving loans']
Columna 'CODE_GENDER':['F' 'M']
Columna 'FLAG_OWN_CAR':['N' 'Y']
Columna 'FLAG_OWN_REALTY':['Y' 'N']
Columna 'CNT_CHILDREN':[ 0  2  1  3  8  4  6  5  7 20 11]
Columna 'NAME_TYPE_SUITE':['Unaccompanied' nan 'Family' 'Spouse, partner' 'Group of people'
 'Other_B' 'Children' 'Other_A']
Columna 'NAME_INCOME_TYPE':['Working' 'State servant' 'Pensioner' 'Commercial associate'
 'Businessman' 'Student' 'Unemployed']
Columna 'NAME_EDUCATION_TYPE':['Higher education' 'Secondary / secondary special' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
Columna 'NAME_FAMILY_STATUS':['Married' 'Single / not married' 'Civil marriage' 'Widow' 'Separated']
Columna 'NAME_HOUSING_TYPE':['House / apartment' 'With parents' 'Rented apartment'
 'Municipal apartment' 'Office apartment' 'Co-op apartment']
Columna 'DAYS_BIRTH':[-19241 -18064 -20038 ... -24168  -9192 -16019]
Columna 'DAYS_EMPLOYED':[-2329 -4469 -4458 ... -7435 -7172 -6551]
Columna 'DAYS_REGISTRATION':[ -5170.  -9118.  -2175. ...  -3481.  -9385. -12088.]
Columna 'DAYS_ID_PUBLISH':[ -812 -1623 -3503 ... -5384 -5228 -6120]
Columna 'OWN_CAR_AGE':[nan  5. 16. 10.  3. 14. 11. 15.  8. 20. 22.  1. 19.  0. 21. 13.  4.  6.
  9. 42. 24.  2. 23. 17. 29. 35. 31. 65.  7. 26. 25. 18. 12. 30. 36. 34.
 32. 28. 39. 27. 37. 41. 40. 50. 38. 56. 33. 74. 43. 44. 55. 49. 52.]
Columna 'FLAG_MOBIL':[1 0]
Columna 'FLAG_EMP_PHONE':[1 0]
Columna 'FLAG_WORK_PHONE':[0 1]
Columna 'FLAG_CONT_MOBILE':[1 0]
Columna 'FLAG_PHONE':[0 1]
Columna 'FLAG_EMAIL':[1 0]
Columna 'OCCUPATION_TYPE':[nan 'Low-skill Laborers' 'Drivers' 'Sales staff' 'High skill tech staff'
 'Core staff' 'Laborers' 'Managers' 'Accountants' 'Medicine staff'
 'Security staff' 'Private service staff' 'Secretaries' 'Cleaning staff'
 'Cooking staff' 'HR staff' 'Waiters/barmen staff' 'Realty agents'
 'IT staff']
Columna 'CNT_FAM_MEMBERS':[ 2.  4.  3.  1.  5. 10.  6.  7.  8.  9. 21. 13.]
Columna 'REGION_RATING_CLIENT':[2 1 3]
Columna 'REGION_RATING_CLIENT_W_CITY':[ 2  1  3 -1]
Columna 'WEEKDAY_APPR_PROCESS_START':['TUESDAY' 'FRIDAY' 'MONDAY' 'WEDNESDAY' 'THURSDAY' 'SATURDAY' 'SUNDAY']
Columna 'HOUR_APPR_PROCESS_START':[18  9 14 11  5 15  7 17 10 12 13  8  4 19 16  3  6  2 23 20 21 22  1  0]
Columna 'REG_REGION_NOT_LIVE_REGION':[0 1]
Columna 'REG_REGION_NOT_WORK_REGION':[0 1]
Columna 'LIVE_REGION_NOT_WORK_REGION':[0 1]
Columna 'REG_CITY_NOT_LIVE_CITY':[0 1]
Columna 'REG_CITY_NOT_WORK_CITY':[0 1]
Columna 'LIVE_CITY_NOT_WORK_CITY':[0 1]
Columna 'ORGANIZATION_TYPE':['Kindergarten' 'Self-employed' 'Transport: type 3'
 'Business Entity Type 3' 'Government' 'Industry: type 9' 'School'
 'Trade: type 2' 'XNA' 'Services' 'Bank' 'Industry: type 3' 'Other'
 'Trade: type 6' 'Industry: type 12' 'Trade: type 7' 'Postal' 'Medicine'
 'Housing' 'Business Entity Type 2' 'Construction' 'Military'
 'Industry: type 4' 'Trade: type 3' 'Legal Services' 'Security'
 'Industry: type 11' 'University' 'Business Entity Type 1' 'Agriculture'
 'Security Ministries' 'Transport: type 2' 'Industry: type 7'
 'Transport: type 4' 'Telecom' 'Emergency' 'Police' 'Industry: type 1'
 'Transport: type 1' 'Electricity' 'Industry: type 5' 'Hotel' 'Restaurant'
 'Advertising' 'Mobile' 'Trade: type 1' 'Industry: type 8' 'Realtor'
 'Cleaning' 'Industry: type 2' 'Trade: type 4' 'Industry: type 6'
 'Culture' 'Insurance' 'Religion' 'Industry: type 13' 'Industry: type 10'
 'Trade: type 5']
Columna 'FONDKAPREMONT_MODE':[nan 'reg oper account' 'not specified' 'org spec account'
 'reg oper spec account']
Columna 'HOUSETYPE_MODE':['block of flats' nan 'specific housing' 'terraced house']
Columna 'WALLSMATERIAL_MODE':['Stone, brick' nan 'Panel' 'Block' 'Wooden' 'Mixed' 'Monolithic' 'Others']
Columna 'EMERGENCYSTATE_MODE':['No' nan 'Yes']
Columna 'OBS_30_CNT_SOCIAL_CIRCLE':[  0.   1.   4.   5.   2.   7.  10.   6.   3.  17.   9.  12.  14.   8.
  18.  23.  11.  13.  15.  nan  16.  20.  19.  29.  21.  22. 353. 354.
 352.]
Columna 'DEF_30_CNT_SOCIAL_CIRCLE':[ 0.  1.  2.  3.  4. nan  5.  6. 34.]
Columna 'OBS_60_CNT_SOCIAL_CIRCLE':[  0.   1.   4.   5.   2.   7.   9.   6.   3.  16.  12.  10.  14.   8.
  18.  23.  11.  13.  17.  15.  nan  20.  19.  29.  21.  22. 349. 351.]
Columna 'DEF_60_CNT_SOCIAL_CIRCLE':[ 0.  1.  3.  2.  4. nan  5. 24.]
Columna 'DAYS_LAST_PHONE_CHANGE':[-1740.     0.  -856. ... -3540. -2905. -2671.]
Columna 'FLAG_DOCUMENT_2':[0]
Columna 'FLAG_DOCUMENT_3':[1 0]
Columna 'FLAG_DOCUMENT_4':[0 1]
Columna 'FLAG_DOCUMENT_5':[0 1]
Columna 'FLAG_DOCUMENT_6':[0 1]
Columna 'FLAG_DOCUMENT_7':[0 1]
Columna 'FLAG_DOCUMENT_8':[0 1]
Columna 'FLAG_DOCUMENT_9':[0 1]
Columna 'FLAG_DOCUMENT_10':[0]
Columna 'FLAG_DOCUMENT_11':[0 1]
Columna 'FLAG_DOCUMENT_12':[0]
Columna 'FLAG_DOCUMENT_13':[0]
Columna 'FLAG_DOCUMENT_14':[0]
Columna 'FLAG_DOCUMENT_15':[0]
Columna 'FLAG_DOCUMENT_16':[0]
Columna 'FLAG_DOCUMENT_17':[0]
Columna 'FLAG_DOCUMENT_18':[0 1]
Columna 'FLAG_DOCUMENT_19':[0]
Columna 'FLAG_DOCUMENT_20':[0]
Columna 'FLAG_DOCUMENT_21':[0]
Columna 'AMT_REQ_CREDIT_BUREAU_HOUR':[ 0. nan  1.  2.]
Columna 'AMT_REQ_CREDIT_BUREAU_DAY':[ 0. nan  1.  2.]
Columna 'AMT_REQ_CREDIT_BUREAU_WEEK':[ 0. nan  1.  2.]
Columna 'AMT_REQ_CREDIT_BUREAU_MON':[ 0. nan  1.  3.  2.  6.  4.  5.]
Columna 'AMT_REQ_CREDIT_BUREAU_QRT':[ 0.  1. nan  3.  2.  4.  5.  7.  6.]
Columna 'AMT_REQ_CREDIT_BUREAU_YEAR':[ 0.  3.  4. nan  2.  1.  5.  6.  7.  9.  8. 10. 11. 13. 12. 17. 14.]

In [7]:
# Obtención de valores únicos para atributos categóricos.
for column in df.columns:
    # Evaluación si el tipo es string.
    if df[column].dtype == 'object':
        unique_values = df[column].unique()
        print(f"Columna '{column}': {unique_values}")

Columna 'NAME_CONTRACT_TYPE': ['Cash loans' 'Revolving loans']
Columna 'CODE_GENDER': ['F' 'M']
Columna 'FLAG_OWN_CAR': ['N' 'Y']
Columna 'FLAG_OWN_REALTY': ['Y' 'N']
Columna 'NAME_TYPE_SUITE': ['Unaccompanied' nan 'Family' 'Spouse, partner' 'Group of people'
 'Other_B' 'Children' 'Other_A']
Columna 'NAME_INCOME_TYPE': ['Working' 'State servant' 'Pensioner' 'Commercial associate'
 'Businessman' 'Student' 'Unemployed']
Columna 'NAME_EDUCATION_TYPE': ['Higher education' 'Secondary / secondary special' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
Columna 'NAME_FAMILY_STATUS': ['Married' 'Single / not married' 'Civil marriage' 'Widow' 'Separated']
Columna 'NAME_HOUSING_TYPE': ['House / apartment' 'With parents' 'Rented apartment'
 'Municipal apartment' 'Office apartment' 'Co-op apartment']
Columna 'OCCUPATION_TYPE': [nan 'Low-skill Laborers' 'Drivers' 'Sales staff' 'High skill tech staff'
 'Core staff' 'Laborers' 'Managers' 'Accountants' 'Medicine staff'
 'Security staff' 'Private service staff' 'Secretaries' 'Cleaning staff'
 'Cooking staff' 'HR staff' 'Waiters/barmen staff' 'Realty agents'
 'IT staff']
Columna 'WEEKDAY_APPR_PROCESS_START': ['TUESDAY' 'FRIDAY' 'MONDAY' 'WEDNESDAY' 'THURSDAY' 'SATURDAY' 'SUNDAY']
Columna 'ORGANIZATION_TYPE': ['Kindergarten' 'Self-employed' 'Transport: type 3'
 'Business Entity Type 3' 'Government' 'Industry: type 9' 'School'
 'Trade: type 2' 'XNA' 'Services' 'Bank' 'Industry: type 3' 'Other'
 'Trade: type 6' 'Industry: type 12' 'Trade: type 7' 'Postal' 'Medicine'
 'Housing' 'Business Entity Type 2' 'Construction' 'Military'
 'Industry: type 4' 'Trade: type 3' 'Legal Services' 'Security'
 'Industry: type 11' 'University' 'Business Entity Type 1' 'Agriculture'
 'Security Ministries' 'Transport: type 2' 'Industry: type 7'
 'Transport: type 4' 'Telecom' 'Emergency' 'Police' 'Industry: type 1'
 'Transport: type 1' 'Electricity' 'Industry: type 5' 'Hotel' 'Restaurant'
 'Advertising' 'Mobile' 'Trade: type 1' 'Industry: type 8' 'Realtor'
 'Cleaning' 'Industry: type 2' 'Trade: type 4' 'Industry: type 6'
 'Culture' 'Insurance' 'Religion' 'Industry: type 13' 'Industry: type 10'
 'Trade: type 5']
Columna 'FONDKAPREMONT_MODE': [nan 'reg oper account' 'not specified' 'org spec account'
 'reg oper spec account']
Columna 'HOUSETYPE_MODE': ['block of flats' nan 'specific housing' 'terraced house']
Columna 'WALLSMATERIAL_MODE': ['Stone, brick' nan 'Panel' 'Block' 'Wooden' 'Mixed' 'Monolithic' 'Others']
Columna 'EMERGENCYSTATE_MODE': ['No' nan 'Yes']

### Primera forma normal

Del analisis realizado, se observó que el atributo "ORGANIZATION_TYPE" no contiene múltiples valores asociados entre sí. Por lo tanto, se incorpora una nueva columna para atomizar los valores.

In [8]:
# Creación de columna ORGANIZATION_TYPE_2 y atomización de valores.

def get_organization_type_2(org_type):
    if pd.isna(org_type):
        return 'Type 0' # Manejar valores NaN

    org_type_lower = str(org_type).lower()
    match_value = re.search(r'type\s*(\d+)', org_type_lower)
    if match_value:
        return f"Type {match_value.group(1)}"
    else:
        return "Type 0"

def clean_organization_type(org_type):
    if pd.isna(org_type):
        return org_type # Mantener valores NaN tal cual

    org_type_str = str(org_type)
    # Eliminar el patrón "type X", considerando dos puntos/espacios opcionales y sin importar mayúsculas/minúsculas
    cleaned_org_type = re.sub(r'[:-]?\s*type\s*\d+', '', org_type_str, flags=re.IGNORECASE).strip()
    # Si la cadena queda vacía después de limpiar (por ejemplo, si era solo "Type 1"), devolver la original
    return cleaned_org_type if cleaned_org_type else org_type_str

df['ORGANIZATION_TYPE_2'] = df['ORGANIZATION_TYPE'].apply(get_organization_type_2)
df['ORGANIZATION_TYPE'] = df['ORGANIZATION_TYPE'].apply(clean_organization_type)

In [9]:
# Print de valores únicos para verificar.
print(df['ORGANIZATION_TYPE'].value_counts(), end='\n\n')
print(df['ORGANIZATION_TYPE_2'].value_counts())

ORGANIZATION_TYPE
Business Entity        13206
XNA                     9274
Self-employed           5920
Other                   2707
Trade                   2332
Industry                2277
Medicine                1716
Transport               1541
Government              1508
School                  1287
Construction            1039
Kindergarten            1038
Military                 530
Security                 472
Police                   441
Housing                  435
Bank                     374
Security Ministries      341
Services                 302
Postal                   294
Agriculture              292
Restaurant               284
University               221
Electricity              156
Hotel                    134
Telecom                   95
Emergency                 91
Insurance                 80
Realtor                   72
Advertising               71
Culture                   61
Legal Services            53
Mobile                    45
Cleaning                  43
Religion                  12
Name: count, dtype: int64

ORGANIZATION_TYPE_2
Type 0     29388
Type 3     12081
Type 2      2246
Type 7      1520
Type 1      1164
Type 4      1065
Type 9       499
Type 11      416
Type 6       149
Type 5       106
Type 12       77
Type 10       24
Type 13        6
Type 8         3
Name: count, dtype: int64

### Segunda forma normal

No se detectaron dependencias parciales del análisis del dataset. Por lo tanto, no se realizaron modificaciones para transformar la base de acuerdo a la segunda forma normal.

### Tercera forma normal

La tercera forma normal requiere la eliminación de las dependencias transitivas entre atributos diferentes a la primary key. Del análisis no resultaron dependencias de esta naturaleza.

### Mejoras de diseño

In [10]:
# Creación de copia para control posterior.
df_backup = df.copy()

In [11]:
# Obtención de atributos categoricos.
dimension_tables = {}
categorical_columns = [col for col in df.columns if df[col].dtype == 'object']

In [12]:
# Creación de tablas de dimensiones.
for col in categorical_columns:
    # Extraer valores únicos no NaN para la tabla de dimensión
    unique_values = df[col].dropna().unique()

    if len(unique_values) > 0:
        # Crear una tabla de dimensión para la columna categórica actual
        dim_df = pd.DataFrame({
            f'{col}_ID': range(1, len(unique_values) + 1),
            col: unique_values
        })
        dimension_tables[f'dim_{col.lower()}'] = dim_df

        # Crear un mapeo desde el valor original al nuevo ID, manejando NaN
        mapping = dict(zip(dim_df[col], dim_df[f'{col}_ID']))

        # Reemplazar los valores categóricos en el DataFrame original con sus IDs
        # Usar .map() que maneja valores NaN por defecto, preservándolos si no están en el mapeo
        df[col] = df[col].map(mapping)

        # Renombrar la columna para reflejar que ahora contiene IDs
        df.rename(columns={col: f'{col}_ID'}, inplace=True)
    else:
        print(f"La columna '{col}' no tiene valores únicos que no estén vacios, por lo tanto se omite la creación de la tabla de dimensión.")

In [13]:
# Control de atributos.
print(f'Recuento de columnas categoricas: {len(categorical_columns)}')
print(f'Recuento de tablas de dimensiones: {len(dimension_tables)}')

Recuento de columnas categoricas: 17
Recuento de tablas de dimensiones: 17

In [14]:
# Tablas de dimensiones.
print(f'Tablas de dimensiones: {[*dimension_tables.keys()]}')

Tablas de dimensiones: ['dim_name_contract_type', 'dim_code_gender', 'dim_flag_own_car', 'dim_flag_own_realty', 'dim_name_type_suite', 'dim_name_income_type', 'dim_name_education_type', 'dim_name_family_status', 'dim_name_housing_type', 'dim_occupation_type', 'dim_weekday_appr_process_start', 'dim_organization_type', 'dim_fondkapremont_mode', 'dim_housetype_mode', 'dim_wallsmaterial_mode', 'dim_emergencystate_mode', 'dim_organization_type_2']

In [15]:
# Print de atributos del dataset backup.
print(f'Columnas del dataset de referencia: {[*df_backup.columns]}')

Columnas del dataset de referencia: ['SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR', 'ORGANIZATION_TYPE_2']

In [16]:
# Query para la verificación del join de tablas principal y de dimensiones.
query = f"""
SELECT {', '.join(df_backup.columns)}
FROM df
"""

dim_tables_names = [*dimension_tables.keys()]

for dim_table_name in dim_tables_names:
  dim_table_id = dimension_tables[dim_table_name].columns[0]

  query += f"""
  LEFT JOIN {dim_table_name} ON df.{dim_table_id} = {dim_table_name}.{dim_table_id}
  """

In [17]:
# Impresion de la query.
print(query)

SELECT SK_ID_CURR, NAME_CONTRACT_TYPE, CODE_GENDER, FLAG_OWN_CAR, FLAG_OWN_REALTY, CNT_CHILDREN, AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY, AMT_GOODS_PRICE, NAME_TYPE_SUITE, NAME_INCOME_TYPE, NAME_EDUCATION_TYPE, NAME_FAMILY_STATUS, NAME_HOUSING_TYPE, REGION_POPULATION_RELATIVE, DAYS_BIRTH, DAYS_EMPLOYED, DAYS_REGISTRATION, DAYS_ID_PUBLISH, OWN_CAR_AGE, FLAG_MOBIL, FLAG_EMP_PHONE, FLAG_WORK_PHONE, FLAG_CONT_MOBILE, FLAG_PHONE, FLAG_EMAIL, OCCUPATION_TYPE, CNT_FAM_MEMBERS, REGION_RATING_CLIENT, REGION_RATING_CLIENT_W_CITY, WEEKDAY_APPR_PROCESS_START, HOUR_APPR_PROCESS_START, REG_REGION_NOT_LIVE_REGION, REG_REGION_NOT_WORK_REGION, LIVE_REGION_NOT_WORK_REGION, REG_CITY_NOT_LIVE_CITY, REG_CITY_NOT_WORK_CITY, LIVE_CITY_NOT_WORK_CITY, ORGANIZATION_TYPE, EXT_SOURCE_1, EXT_SOURCE_2, EXT_SOURCE_3, APARTMENTS_AVG, BASEMENTAREA_AVG, YEARS_BEGINEXPLUATATION_AVG, YEARS_BUILD_AVG, COMMONAREA_AVG, ELEVATORS_AVG, ENTRANCES_AVG, FLOORSMAX_AVG, FLOORSMIN_AVG, LANDAREA_AVG, LIVINGAPARTMENTS_AVG, LIVINGAREA_AVG, NONLIVINGAPARTMENTS_AVG, NONLIVINGAREA_AVG, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MODE, YEARS_BUILD_MODE, COMMONAREA_MODE, ELEVATORS_MODE, ENTRANCES_MODE, FLOORSMAX_MODE, FLOORSMIN_MODE, LANDAREA_MODE, LIVINGAPARTMENTS_MODE, LIVINGAREA_MODE, NONLIVINGAPARTMENTS_MODE, NONLIVINGAREA_MODE, APARTMENTS_MEDI, BASEMENTAREA_MEDI, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MEDI, COMMONAREA_MEDI, ELEVATORS_MEDI, ENTRANCES_MEDI, FLOORSMAX_MEDI, FLOORSMIN_MEDI, LANDAREA_MEDI, LIVINGAPARTMENTS_MEDI, LIVINGAREA_MEDI, NONLIVINGAPARTMENTS_MEDI, NONLIVINGAREA_MEDI, FONDKAPREMONT_MODE, HOUSETYPE_MODE, TOTALAREA_MODE, WALLSMATERIAL_MODE, EMERGENCYSTATE_MODE, OBS_30_CNT_SOCIAL_CIRCLE, DEF_30_CNT_SOCIAL_CIRCLE, OBS_60_CNT_SOCIAL_CIRCLE, DEF_60_CNT_SOCIAL_CIRCLE, DAYS_LAST_PHONE_CHANGE, FLAG_DOCUMENT_2, FLAG_DOCUMENT_3, FLAG_DOCUMENT_4, FLAG_DOCUMENT_5, FLAG_DOCUMENT_6, FLAG_DOCUMENT_7, FLAG_DOCUMENT_8, FLAG_DOCUMENT_9, FLAG_DOCUMENT_10, FLAG_DOCUMENT_11, FLAG_DOCUMENT_12, FLAG_DOCUMENT_13, FLAG_DOCUMENT_14, FLAG_DOCUMENT_15, FLAG_DOCUMENT_16, FLAG_DOCUMENT_17, FLAG_DOCUMENT_18, FLAG_DOCUMENT_19, FLAG_DOCUMENT_20, FLAG_DOCUMENT_21, AMT_REQ_CREDIT_BUREAU_HOUR, AMT_REQ_CREDIT_BUREAU_DAY, AMT_REQ_CREDIT_BUREAU_WEEK, AMT_REQ_CREDIT_BUREAU_MON, AMT_REQ_CREDIT_BUREAU_QRT, AMT_REQ_CREDIT_BUREAU_YEAR, ORGANIZATION_TYPE_2
FROM df

  LEFT JOIN dim_name_contract_type ON df.NAME_CONTRACT_TYPE_ID = dim_name_contract_type.NAME_CONTRACT_TYPE_ID

  LEFT JOIN dim_code_gender ON df.CODE_GENDER_ID = dim_code_gender.CODE_GENDER_ID

  LEFT JOIN dim_flag_own_car ON df.FLAG_OWN_CAR_ID = dim_flag_own_car.FLAG_OWN_CAR_ID

  LEFT JOIN dim_flag_own_realty ON df.FLAG_OWN_REALTY_ID = dim_flag_own_realty.FLAG_OWN_REALTY_ID

  LEFT JOIN dim_name_type_suite ON df.NAME_TYPE_SUITE_ID = dim_name_type_suite.NAME_TYPE_SUITE_ID

  LEFT JOIN dim_name_income_type ON df.NAME_INCOME_TYPE_ID = dim_name_income_type.NAME_INCOME_TYPE_ID

  LEFT JOIN dim_name_education_type ON df.NAME_EDUCATION_TYPE_ID = dim_name_education_type.NAME_EDUCATION_TYPE_ID

  LEFT JOIN dim_name_family_status ON df.NAME_FAMILY_STATUS_ID = dim_name_family_status.NAME_FAMILY_STATUS_ID

  LEFT JOIN dim_name_housing_type ON df.NAME_HOUSING_TYPE_ID = dim_name_housing_type.NAME_HOUSING_TYPE_ID

  LEFT JOIN dim_occupation_type ON df.OCCUPATION_TYPE_ID = dim_occupation_type.OCCUPATION_TYPE_ID

  LEFT JOIN dim_weekday_appr_process_start ON df.WEEKDAY_APPR_PROCESS_START_ID = dim_weekday_appr_process_start.WEEKDAY_APPR_PROCESS_START_ID

  LEFT JOIN dim_organization_type ON df.ORGANIZATION_TYPE_ID = dim_organization_type.ORGANIZATION_TYPE_ID

  LEFT JOIN dim_fondkapremont_mode ON df.FONDKAPREMONT_MODE_ID = dim_fondkapremont_mode.FONDKAPREMONT_MODE_ID

  LEFT JOIN dim_housetype_mode ON df.HOUSETYPE_MODE_ID = dim_housetype_mode.HOUSETYPE_MODE_ID

  LEFT JOIN dim_wallsmaterial_mode ON df.WALLSMATERIAL_MODE_ID = dim_wallsmaterial_mode.WALLSMATERIAL_MODE_ID

  LEFT JOIN dim_emergencystate_mode ON df.EMERGENCYSTATE_MODE_ID = dim_emergencystate_mode.EMERGENCYSTATE_MODE_ID

  LEFT JOIN dim_organization_type_2 ON df.ORGANIZATION_TYPE_2_ID = dim_organization_type_2.ORGANIZATION_TYPE_2_ID

In [18]:
# Control de join de tablas descompuestas.

# Construcción de diccionario con dataframe principal y dataframes de dimensiones.
env = {**dimension_tables, 'df': df}

# Ejecución de la query.
control_df = sqldf(query, env) # sqldf(query, locals())
control_df.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,ORGANIZATION_TYPE_2
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Type 0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,Type 0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0,Type 3
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,Type 3
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,Type 3

In [19]:
# Shape de control_df.
control_df.shape

(48744, 122)

In [20]:
# Reemplazo de NoneType por np.nans.
for col in control_df.columns:
    # Verificacion si 'None' (NoneType) está presente en la columna.
    if control_df[col].apply(lambda x: x is None).any():
        control_df[col] = control_df[col].replace({None: np.nan})

print("Valores None fueron reemplazados con np.nan para todas las columnas de control_df.")

Valores None fueron reemplazados con np.nan para todas las columnas de control_df.

In [21]:
# Cotejo final de control_df con df_backup.

matching_counts = {}

# Asegurar que solo comparamos las columnas que existen en ambos DataFrames.
columns_to_compare = [col for col in df_backup.columns if col in control_df.columns]

for col in columns_to_compare:
    s1 = control_df[col]
    s2 = df_backup[col]

    # Comparar valores, tratando np.nan como iguales si ambos lo son
    # Esto gestiona tanto valores iguales no nulos (s1 == s2) como coincidencias NaN-NaN (s1.isna() & s2.isna())
    matches = ((s1 == s2) | (s1.isna() & s2.isna()))
    matching_counts[col] = matches.sum()

# Crear un DataFrame para visualizar mejor los resultados
comparison_df = pd.DataFrame(matching_counts.items(), columns=['Column', 'Matching_Count'])
comparison_df['Total_Rows'] = len(df_backup)
comparison_df['Percentage_Match'] = (comparison_df['Matching_Count'] / comparison_df['Total_Rows']) * 100

display(comparison_df)

# Opcionalmente, mostrar columnas que no tienen un 100% de coincidencia para facilitar la inspección
non_full_match_cols = comparison_df[comparison_df['Percentage_Match'] < 100]
if not non_full_match_cols.empty:
    print("\nColumnas con menos del 100% de coincidencia (debido a diferencias reales de valores, no solo manejo de NaN):")
    display(non_full_match_cols)
else:
    print("\nTodas las columnas comparadas tienen una coincidencia del 100% (incluyendo la igualdad NaN-NaN).")

                         Column  Matching_Count  Total_Rows  Percentage_Match
0                    SK_ID_CURR           48744       48744             100.0
1            NAME_CONTRACT_TYPE           48744       48744             100.0
2                   CODE_GENDER           48744       48744             100.0
3                  FLAG_OWN_CAR           48744       48744             100.0
4               FLAG_OWN_REALTY           48744       48744             100.0
..                          ...             ...         ...               ...
117  AMT_REQ_CREDIT_BUREAU_WEEK           48744       48744             100.0
118   AMT_REQ_CREDIT_BUREAU_MON           48744       48744             100.0
119   AMT_REQ_CREDIT_BUREAU_QRT           48744       48744             100.0
120  AMT_REQ_CREDIT_BUREAU_YEAR           48744       48744             100.0
121         ORGANIZATION_TYPE_2           48744       48744             100.0

[122 rows x 4 columns]

Todas las columnas comparadas tienen una coincidencia del 100% (incluyendo la igualdad NaN-NaN).

### Exportación de DataFrames a CSV

Este paso guarda el DataFrame principal y cada una de las tablas de dimensiones creadas en archivos CSV individuales. Esto permite un almacenamiento y uso posterior más sencillo de los datos normalizados y las tablas de referencia.

In [25]:
# Creacion de directorio output.
ref_name = csv_name.replace('.csv', '')
extract_dir = output_dir + ref_name + '/'

# Evaluacion de existencia del directorio.
if not os.path.exists(extract_dir):
    os.makedirs(extract_dir)

# Guardar el dataFrame principal 'df' en un archivo CSV.
df.to_csv(extract_dir + csv_name, index=False)
print(f'DataFrame principal guardado como {csv_name}')

# Guardar cada tabla de dimensiones en un archivo CSV separado
for name, dim_df in dimension_tables.items():
    file_name = f'{name}.csv'
    dim_df.to_csv(extract_dir + file_name, index=False)
    print(f'Tabla de dimensiones "{name}" guardada como {file_name}')

DataFrame principal guardado como application_test.csv
Tabla de dimensiones "dim_name_contract_type" guardada como dim_name_contract_type.csv
Tabla de dimensiones "dim_code_gender" guardada como dim_code_gender.csv
Tabla de dimensiones "dim_flag_own_car" guardada como dim_flag_own_car.csv
Tabla de dimensiones "dim_flag_own_realty" guardada como dim_flag_own_realty.csv
Tabla de dimensiones "dim_name_type_suite" guardada como dim_name_type_suite.csv
Tabla de dimensiones "dim_name_income_type" guardada como dim_name_income_type.csv
Tabla de dimensiones "dim_name_education_type" guardada como dim_name_education_type.csv
Tabla de dimensiones "dim_name_family_status" guardada como dim_name_family_status.csv
Tabla de dimensiones "dim_name_housing_type" guardada como dim_name_housing_type.csv
Tabla de dimensiones "dim_occupation_type" guardada como dim_occupation_type.csv
Tabla de dimensiones "dim_weekday_appr_process_start" guardada como dim_weekday_appr_process_start.csv
Tabla de dimensiones "dim_organization_type" guardada como dim_organization_type.csv
Tabla de dimensiones "dim_fondkapremont_mode" guardada como dim_fondkapremont_mode.csv
Tabla de dimensiones "dim_housetype_mode" guardada como dim_housetype_mode.csv
Tabla de dimensiones "dim_wallsmaterial_mode" guardada como dim_wallsmaterial_mode.csv
Tabla de dimensiones "dim_emergencystate_mode" guardada como dim_emergencystate_mode.csv
Tabla de dimensiones "dim_organization_type_2" guardada como dim_organization_type_2.csv

# Application_train

### Analisis de datos preliminar

In [26]:
# Lectura del dataset.
csv_name = 'application_train.csv'
df = pd.read_csv(data_path + csv_name)

# Head del dataset.
df.info()

# Head del dataset.
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
# Obtención de valores únicos para atributos categóricos y numéricos no float.
for column in df.columns:
    unique_values = df[column].unique()

    # Indicador para verificar si la columna contiene algún valor float no entero (excluyendo NaN)
    contains_non_integer_float = False

    # Iterar sobre los valores únicos para encontrar floats no enteros
    for val in unique_values:
        # Verificar si el valor es un float y no es NaN
        if isinstance(val, float) and not np.isnan(val):
            # Verificar si el float tiene una parte decimal distinta de cero
            if val != int(val):
                contains_non_integer_float = True
                break  # Se encontró un float no entero, no es necesario seguir verificando

    # Si no se encontró ningún float no entero, imprimir los valores únicos de la columna
    if not contains_non_integer_float:
        print(f"Columna '{column}':{unique_values}")

Columna 'SK_ID_CURR':[100002 100003 100004 ... 456253 456254 456255]
Columna 'TARGET':[1 0]
Columna 'NAME_CONTRACT_TYPE':['Cash loans' 'Revolving loans']
Columna 'CODE_GENDER':['M' 'F' 'XNA']
Columna 'FLAG_OWN_CAR':['N' 'Y']
Columna 'FLAG_OWN_REALTY':['Y' 'N']
Columna 'CNT_CHILDREN':[ 0  1  2  3  4  7  5  6  8  9 11 12 10 19 14]
Columna 'NAME_TYPE_SUITE':['Unaccompanied' 'Family' 'Spouse, partner' 'Children' 'Other_A' nan
 'Other_B' 'Group of people']
Columna 'NAME_INCOME_TYPE':['Working' 'State servant' 'Commercial associate' 'Pensioner' 'Unemployed'
 'Student' 'Businessman' 'Maternity leave']
Columna 'NAME_EDUCATION_TYPE':['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
Columna 'NAME_FAMILY_STATUS':['Single / not married' 'Married' 'Civil marriage' 'Widow' 'Separated'
 'Unknown']
Columna 'NAME_HOUSING_TYPE':['House / apartment' 'Rented apartment' 'With parents'
 'Municipal apartment' 'Office apartment' 'Co-op apartment']
Columna 'DAYS_BIRTH':[ -9461 -16765 -19046 ...  -7951  -7857 -25061]
Columna 'DAYS_EMPLOYED':[  -637  -1188   -225 ... -12971 -11084  -8694]
Columna 'DAYS_ID_PUBLISH':[-2120  -291 -2531 ... -6194 -5854 -6211]
Columna 'OWN_CAR_AGE':[nan 26. 17.  8. 23.  7. 14.  1.  3. 13. 10.  2. 21. 20. 22. 65.  5. 11.
  9.  4. 15. 12. 25.  6. 64.  0. 27. 19. 28. 18. 16. 30. 36. 24. 39. 29.
 40. 41. 31. 42. 37. 35. 34. 33. 54. 38. 32. 43. 55. 49. 44. 63. 46. 45.
 48. 56. 51. 57. 69. 50. 47. 91. 52.]
Columna 'FLAG_MOBIL':[1 0]
Columna 'FLAG_EMP_PHONE':[1 0]
Columna 'FLAG_WORK_PHONE':[0 1]
Columna 'FLAG_CONT_MOBILE':[1 0]
Columna 'FLAG_PHONE':[1 0]
Columna 'FLAG_EMAIL':[0 1]
Columna 'OCCUPATION_TYPE':['Laborers' 'Core staff' 'Accountants' 'Managers' nan 'Drivers'
 'Sales staff' 'Cleaning staff' 'Cooking staff' 'Private service staff'
 'Medicine staff' 'Security staff' 'High skill tech staff'
 'Waiters/barmen staff' 'Low-skill Laborers' 'Realty agents' 'Secretaries'
 'IT staff' 'HR staff']
Columna 'CNT_FAM_MEMBERS':[ 1.  2.  3.  4.  5.  6.  9.  7.  8. 10. 13. nan 14. 12. 20. 15. 16. 11.]
Columna 'REGION_RATING_CLIENT':[2 1 3]
Columna 'REGION_RATING_CLIENT_W_CITY':[2 1 3]
Columna 'WEEKDAY_APPR_PROCESS_START':['WEDNESDAY' 'MONDAY' 'THURSDAY' 'SUNDAY' 'SATURDAY' 'FRIDAY' 'TUESDAY']
Columna 'HOUR_APPR_PROCESS_START':[10 11  9 17 16 14  8 15  7 13  6 12 19  3 18 21  4  5 20 22  1  2 23  0]
Columna 'REG_REGION_NOT_LIVE_REGION':[0 1]
Columna 'REG_REGION_NOT_WORK_REGION':[0 1]
Columna 'LIVE_REGION_NOT_WORK_REGION':[0 1]
Columna 'REG_CITY_NOT_LIVE_CITY':[0 1]
Columna 'REG_CITY_NOT_WORK_CITY':[0 1]
Columna 'LIVE_CITY_NOT_WORK_CITY':[0 1]
Columna 'ORGANIZATION_TYPE':['Business Entity Type 3' 'School' 'Government' 'Religion' 'Other' 'XNA'
 'Electricity' 'Medicine' 'Business Entity Type 2' 'Self-employed'
 'Transport: type 2' 'Construction' 'Housing' 'Kindergarten'
 'Trade: type 7' 'Industry: type 11' 'Military' 'Services'
 'Security Ministries' 'Transport: type 4' 'Industry: type 1' 'Emergency'
 'Security' 'Trade: type 2' 'University' 'Transport: type 3' 'Police'
 'Business Entity Type 1' 'Postal' 'Industry: type 4' 'Agriculture'
 'Restaurant' 'Culture' 'Hotel' 'Industry: type 7' 'Trade: type 3'
 'Industry: type 3' 'Bank' 'Industry: type 9' 'Insurance' 'Trade: type 6'
 'Industry: type 2' 'Transport: type 1' 'Industry: type 12' 'Mobile'
 'Trade: type 1' 'Industry: type 5' 'Industry: type 10' 'Legal Services'
 'Advertising' 'Trade: type 5' 'Cleaning' 'Industry: type 13'
 'Trade: type 4' 'Telecom' 'Industry: type 8' 'Realtor' 'Industry: type 6']
Columna 'FONDKAPREMONT_MODE':['reg oper account' nan 'org spec account' 'reg oper spec account'
 'not specified']
Columna 'HOUSETYPE_MODE':['block of flats' nan 'terraced house' 'specific housing']
Columna 'WALLSMATERIAL_MODE':['Stone, brick' 'Block' nan 'Panel' 'Mixed' 'Wooden' 'Others' 'Monolithic']
Columna 'EMERGENCYSTATE_MODE':['No' nan 'Yes']
Columna 'OBS_30_CNT_SOCIAL_CIRCLE':[  2.   1.   0.   4.   8.  10.  nan   7.   3.   6.   5.  12.   9.  13.
  11.  14.  22.  16.  15.  17.  20.  25.  19.  18.  21.  24.  23.  28.
  26.  29.  27.  47. 348.  30.]
Columna 'DEF_30_CNT_SOCIAL_CIRCLE':[ 2.  0.  1. nan  3.  4.  5.  6.  7. 34.  8.]
Columna 'OBS_60_CNT_SOCIAL_CIRCLE':[  2.   1.   0.   4.   8.  10.  nan   7.   3.   6.   5.  12.   9.  13.
  11.  14.  21.  15.  22.  16.  20.  25.  17.  19.  18.  24.  23.  28.
  29.  27.  47. 344.  30.  26.]
Columna 'DEF_60_CNT_SOCIAL_CIRCLE':[ 2.  0.  1. nan  3.  5.  4.  7. 24.  6.]
Columna 'DAYS_LAST_PHONE_CHANGE':[-1134.  -828.  -815. ... -3988. -3899. -3538.]
Columna 'FLAG_DOCUMENT_2':[0 1]
Columna 'FLAG_DOCUMENT_3':[1 0]
Columna 'FLAG_DOCUMENT_4':[0 1]
Columna 'FLAG_DOCUMENT_5':[0 1]
Columna 'FLAG_DOCUMENT_6':[0 1]
Columna 'FLAG_DOCUMENT_7':[0 1]
Columna 'FLAG_DOCUMENT_8':[0 1]
Columna 'FLAG_DOCUMENT_9':[0 1]
Columna 'FLAG_DOCUMENT_10':[0 1]
Columna 'FLAG_DOCUMENT_11':[0 1]
Columna 'FLAG_DOCUMENT_12':[0 1]
Columna 'FLAG_DOCUMENT_13':[0 1]
Columna 'FLAG_DOCUMENT_14':[0 1]
Columna 'FLAG_DOCUMENT_15':[0 1]
Columna 'FLAG_DOCUMENT_16':[0 1]
Columna 'FLAG_DOCUMENT_17':[0 1]
Columna 'FLAG_DOCUMENT_18':[0 1]
Columna 'FLAG_DOCUMENT_19':[0 1]
Columna 'FLAG_DOCUMENT_20':[0 1]
Columna 'FLAG_DOCUMENT_21':[0 1]
Columna 'AMT_REQ_CREDIT_BUREAU_HOUR':[ 0. nan  1.  2.  3.  4.]
Columna 'AMT_REQ_CREDIT_BUREAU_DAY':[ 0. nan  1.  3.  2.  4.  5.  6.  9.  8.]
Columna 'AMT_REQ_CREDIT_BUREAU_WEEK':[ 0. nan  1.  3.  2.  4.  5.  6.  8.  7.]
Columna 'AMT_REQ_CREDIT_BUREAU_MON':[ 0. nan  1.  2.  6.  5.  3.  7.  9.  4. 11.  8. 16. 12. 14. 10. 13. 17.
 24. 19. 15. 23. 18. 27. 22.]
Columna 'AMT_REQ_CREDIT_BUREAU_QRT':[  0.  nan   1.   2.   4.   3.   8.   5.   6.   7. 261.  19.]
Columna 'AMT_REQ_CREDIT_BUREAU_YEAR':[ 1.  0. nan  2.  4.  5.  3.  8.  6.  9.  7. 10. 11. 13. 16. 12. 25. 23.
 15. 14. 22. 17. 19. 18. 21. 20.]

In [28]:
# Obtención de valores únicos para atributos categóricos.
for column in df.columns:
    # Evaluación si el tipo es string.
    if df[column].dtype == 'object':
        unique_values = df[column].unique()
        print(f"Columna '{column}': {unique_values}")

Columna 'NAME_CONTRACT_TYPE': ['Cash loans' 'Revolving loans']
Columna 'CODE_GENDER': ['M' 'F' 'XNA']
Columna 'FLAG_OWN_CAR': ['N' 'Y']
Columna 'FLAG_OWN_REALTY': ['Y' 'N']
Columna 'NAME_TYPE_SUITE': ['Unaccompanied' 'Family' 'Spouse, partner' 'Children' 'Other_A' nan
 'Other_B' 'Group of people']
Columna 'NAME_INCOME_TYPE': ['Working' 'State servant' 'Commercial associate' 'Pensioner' 'Unemployed'
 'Student' 'Businessman' 'Maternity leave']
Columna 'NAME_EDUCATION_TYPE': ['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
Columna 'NAME_FAMILY_STATUS': ['Single / not married' 'Married' 'Civil marriage' 'Widow' 'Separated'
 'Unknown']
Columna 'NAME_HOUSING_TYPE': ['House / apartment' 'Rented apartment' 'With parents'
 'Municipal apartment' 'Office apartment' 'Co-op apartment']
Columna 'OCCUPATION_TYPE': ['Laborers' 'Core staff' 'Accountants' 'Managers' nan 'Drivers'
 'Sales staff' 'Cleaning staff' 'Cooking staff' 'Private service staff'
 'Medicine staff' 'Security staff' 'High skill tech staff'
 'Waiters/barmen staff' 'Low-skill Laborers' 'Realty agents' 'Secretaries'
 'IT staff' 'HR staff']
Columna 'WEEKDAY_APPR_PROCESS_START': ['WEDNESDAY' 'MONDAY' 'THURSDAY' 'SUNDAY' 'SATURDAY' 'FRIDAY' 'TUESDAY']
Columna 'ORGANIZATION_TYPE': ['Business Entity Type 3' 'School' 'Government' 'Religion' 'Other' 'XNA'
 'Electricity' 'Medicine' 'Business Entity Type 2' 'Self-employed'
 'Transport: type 2' 'Construction' 'Housing' 'Kindergarten'
 'Trade: type 7' 'Industry: type 11' 'Military' 'Services'
 'Security Ministries' 'Transport: type 4' 'Industry: type 1' 'Emergency'
 'Security' 'Trade: type 2' 'University' 'Transport: type 3' 'Police'
 'Business Entity Type 1' 'Postal' 'Industry: type 4' 'Agriculture'
 'Restaurant' 'Culture' 'Hotel' 'Industry: type 7' 'Trade: type 3'
 'Industry: type 3' 'Bank' 'Industry: type 9' 'Insurance' 'Trade: type 6'
 'Industry: type 2' 'Transport: type 1' 'Industry: type 12' 'Mobile'
 'Trade: type 1' 'Industry: type 5' 'Industry: type 10' 'Legal Services'
 'Advertising' 'Trade: type 5' 'Cleaning' 'Industry: type 13'
 'Trade: type 4' 'Telecom' 'Industry: type 8' 'Realtor' 'Industry: type 6']
Columna 'FONDKAPREMONT_MODE': ['reg oper account' nan 'org spec account' 'reg oper spec account'
 'not specified']
Columna 'HOUSETYPE_MODE': ['block of flats' nan 'terraced house' 'specific housing']
Columna 'WALLSMATERIAL_MODE': ['Stone, brick' 'Block' nan 'Panel' 'Mixed' 'Wooden' 'Others' 'Monolithic']
Columna 'EMERGENCYSTATE_MODE': ['No' nan 'Yes']

### Primera forma normal

Del analisis realizado, se observó que el atributo "ORGANIZATION_TYPE" no contiene múltiples valores asociados entre sí. Por lo tanto, se incorpora una nueva columna para atomizar los valores.

In [29]:
# Creación de columna ORGANIZATION_TYPE_2 y atomización de valores.

def get_organization_type_2(org_type):
    if pd.isna(org_type):
        return 'Type 0' # Manejar valores NaN

    org_type_lower = str(org_type).lower()
    match_value = re.search(r'type\s*(\d+)', org_type_lower)
    if match_value:
        return f"Type {match_value.group(1)}"
    else:
        return "Type 0"

def clean_organization_type(org_type):
    if pd.isna(org_type):
        return org_type # Mantener valores NaN tal cual

    org_type_str = str(org_type)
    # Eliminar el patrón "type X", considerando dos puntos/espacios opcionales y sin importar mayúsculas/minúsculas
    cleaned_org_type = re.sub(r'[:-]?\s*type\s*\d+', '', org_type_str, flags=re.IGNORECASE).strip()
    # Si la cadena queda vacía después de limpiar (por ejemplo, si era solo "Type 1"), devolver la original
    return cleaned_org_type if cleaned_org_type else org_type_str

df['ORGANIZATION_TYPE_2'] = df['ORGANIZATION_TYPE'].apply(get_organization_type_2)
df['ORGANIZATION_TYPE'] = df['ORGANIZATION_TYPE'].apply(clean_organization_type)

In [30]:
# Print de valores únicos para verificar.
print(df['ORGANIZATION_TYPE'].value_counts(), end='\n\n')
print(df['ORGANIZATION_TYPE_2'].value_counts())

ORGANIZATION_TYPE
Business Entity        84529
XNA                    55374
Self-employed          38412
Other                  16683
Trade                  14315
Industry               14311
Medicine               11193
Government             10404
Transport               8990
School                  8893
Kindergarten            6880
Construction            6721
Security                3247
Housing                 2958
Military                2634
Bank                    2507
Agriculture             2454
Police                  2341
Postal                  2157
Security Ministries     1974
Restaurant              1811
Services                1575
University              1327
Hotel                    966
Electricity              950
Insurance                597
Telecom                  577
Emergency                560
Advertising              429
Realtor                  396
Culture                  379
Mobile                   317
Legal Services           305
Cleaning                 260
Religion                  85
Name: count, dtype: int64

ORGANIZATION_TYPE_2
Type 0     185366
Type 3      75949
Type 2      15115
Type 7       9138
Type 1       7572
Type 4       6339
Type 9       3368
Type 11      2704
Type 6        743
Type 5        648
Type 12       369
Type 10       109
Type 13        67
Type 8         24
Name: count, dtype: int64

### Segunda forma normal

No se detectaron dependencias parciales del análisis del dataset. Por lo tanto, no se realizaron modificaciones para transformar la base de acuerdo a la segunda forma normal.

### Tercera forma normal

La tercera forma normal requiere la eliminación de las dependencias transitivas entre atributos diferentes a la primary key. Del análisis no resultaron dependencias de esta naturaleza.

### Mejoras de diseño

In [31]:
# Creación de copia para control posterior.
df_backup = df.copy()

In [32]:
# Obtención de atributos categoricos.
dimension_tables = {}
categorical_columns = [col for col in df.columns if df[col].dtype == 'object']

In [33]:
# Creación de tablas de dimensiones.
for col in categorical_columns:
    # Extraer valores únicos no NaN para la tabla de dimensión
    unique_values = df[col].dropna().unique()

    if len(unique_values) > 0:
        # Crear una tabla de dimensión para la columna categórica actual
        dim_df = pd.DataFrame({
            f'{col}_ID': range(1, len(unique_values) + 1),
            col: unique_values
        })
        dimension_tables[f'dim_{col.lower()}'] = dim_df

        # Crear un mapeo desde el valor original al nuevo ID, manejando NaN
        mapping = dict(zip(dim_df[col], dim_df[f'{col}_ID']))

        # Reemplazar los valores categóricos en el DataFrame original con sus IDs
        # Usar .map() que maneja valores NaN por defecto, preservándolos si no están en el mapeo
        df[col] = df[col].map(mapping)

        # Renombrar la columna para reflejar que ahora contiene IDs
        df.rename(columns={col: f'{col}_ID'}, inplace=True)
    else:
        print(f"La columna '{col}' no tiene valores únicos que no estén vacios, por lo tanto se omite la creación de la tabla de dimensión.")

In [34]:
# Control de atributos.
print(f'Recuento de columnas categoricas: {len(categorical_columns)}')
print(f'Recuento de tablas de dimensiones: {len(dimension_tables)}')

Recuento de columnas categoricas: 17
Recuento de tablas de dimensiones: 17

In [35]:
# Tablas de dimensiones.
print(f'Tablas de dimensiones: {[*dimension_tables.keys()]}')

Tablas de dimensiones: ['dim_name_contract_type', 'dim_code_gender', 'dim_flag_own_car', 'dim_flag_own_realty', 'dim_name_type_suite', 'dim_name_income_type', 'dim_name_education_type', 'dim_name_family_status', 'dim_name_housing_type', 'dim_occupation_type', 'dim_weekday_appr_process_start', 'dim_organization_type', 'dim_fondkapremont_mode', 'dim_housetype_mode', 'dim_wallsmaterial_mode', 'dim_emergencystate_mode', 'dim_organization_type_2']

In [36]:
# Print de atributos del dataset backup.
print(f'Columnas del dataset de referencia: {[*df_backup.columns]}')

Columnas del dataset de referencia: ['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR', 'ORGANIZATION_TYPE_2']

In [37]:
# Query para la verificación del join de tablas principal y de dimensiones.
query = f"""
SELECT {', '.join(df_backup.columns)}
FROM df
"""

dim_tables_names = [*dimension_tables.keys()]

for dim_table_name in dim_tables_names:
  dim_table_id = dimension_tables[dim_table_name].columns[0]

  query += f"""
  LEFT JOIN {dim_table_name} ON df.{dim_table_id} = {dim_table_name}.{dim_table_id}
  """

In [38]:
# Impresion de la query.
print(query)

SELECT SK_ID_CURR, TARGET, NAME_CONTRACT_TYPE, CODE_GENDER, FLAG_OWN_CAR, FLAG_OWN_REALTY, CNT_CHILDREN, AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY, AMT_GOODS_PRICE, NAME_TYPE_SUITE, NAME_INCOME_TYPE, NAME_EDUCATION_TYPE, NAME_FAMILY_STATUS, NAME_HOUSING_TYPE, REGION_POPULATION_RELATIVE, DAYS_BIRTH, DAYS_EMPLOYED, DAYS_REGISTRATION, DAYS_ID_PUBLISH, OWN_CAR_AGE, FLAG_MOBIL, FLAG_EMP_PHONE, FLAG_WORK_PHONE, FLAG_CONT_MOBILE, FLAG_PHONE, FLAG_EMAIL, OCCUPATION_TYPE, CNT_FAM_MEMBERS, REGION_RATING_CLIENT, REGION_RATING_CLIENT_W_CITY, WEEKDAY_APPR_PROCESS_START, HOUR_APPR_PROCESS_START, REG_REGION_NOT_LIVE_REGION, REG_REGION_NOT_WORK_REGION, LIVE_REGION_NOT_WORK_REGION, REG_CITY_NOT_LIVE_CITY, REG_CITY_NOT_WORK_CITY, LIVE_CITY_NOT_WORK_CITY, ORGANIZATION_TYPE, EXT_SOURCE_1, EXT_SOURCE_2, EXT_SOURCE_3, APARTMENTS_AVG, BASEMENTAREA_AVG, YEARS_BEGINEXPLUATATION_AVG, YEARS_BUILD_AVG, COMMONAREA_AVG, ELEVATORS_AVG, ENTRANCES_AVG, FLOORSMAX_AVG, FLOORSMIN_AVG, LANDAREA_AVG, LIVINGAPARTMENTS_AVG, LIVINGAREA_AVG, NONLIVINGAPARTMENTS_AVG, NONLIVINGAREA_AVG, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MODE, YEARS_BUILD_MODE, COMMONAREA_MODE, ELEVATORS_MODE, ENTRANCES_MODE, FLOORSMAX_MODE, FLOORSMIN_MODE, LANDAREA_MODE, LIVINGAPARTMENTS_MODE, LIVINGAREA_MODE, NONLIVINGAPARTMENTS_MODE, NONLIVINGAREA_MODE, APARTMENTS_MEDI, BASEMENTAREA_MEDI, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MEDI, COMMONAREA_MEDI, ELEVATORS_MEDI, ENTRANCES_MEDI, FLOORSMAX_MEDI, FLOORSMIN_MEDI, LANDAREA_MEDI, LIVINGAPARTMENTS_MEDI, LIVINGAREA_MEDI, NONLIVINGAPARTMENTS_MEDI, NONLIVINGAREA_MEDI, FONDKAPREMONT_MODE, HOUSETYPE_MODE, TOTALAREA_MODE, WALLSMATERIAL_MODE, EMERGENCYSTATE_MODE, OBS_30_CNT_SOCIAL_CIRCLE, DEF_30_CNT_SOCIAL_CIRCLE, OBS_60_CNT_SOCIAL_CIRCLE, DEF_60_CNT_SOCIAL_CIRCLE, DAYS_LAST_PHONE_CHANGE, FLAG_DOCUMENT_2, FLAG_DOCUMENT_3, FLAG_DOCUMENT_4, FLAG_DOCUMENT_5, FLAG_DOCUMENT_6, FLAG_DOCUMENT_7, FLAG_DOCUMENT_8, FLAG_DOCUMENT_9, FLAG_DOCUMENT_10, FLAG_DOCUMENT_11, FLAG_DOCUMENT_12, FLAG_DOCUMENT_13, FLAG_DOCUMENT_14, FLAG_DOCUMENT_15, FLAG_DOCUMENT_16, FLAG_DOCUMENT_17, FLAG_DOCUMENT_18, FLAG_DOCUMENT_19, FLAG_DOCUMENT_20, FLAG_DOCUMENT_21, AMT_REQ_CREDIT_BUREAU_HOUR, AMT_REQ_CREDIT_BUREAU_DAY, AMT_REQ_CREDIT_BUREAU_WEEK, AMT_REQ_CREDIT_BUREAU_MON, AMT_REQ_CREDIT_BUREAU_QRT, AMT_REQ_CREDIT_BUREAU_YEAR, ORGANIZATION_TYPE_2
FROM df

  LEFT JOIN dim_name_contract_type ON df.NAME_CONTRACT_TYPE_ID = dim_name_contract_type.NAME_CONTRACT_TYPE_ID

  LEFT JOIN dim_code_gender ON df.CODE_GENDER_ID = dim_code_gender.CODE_GENDER_ID

  LEFT JOIN dim_flag_own_car ON df.FLAG_OWN_CAR_ID = dim_flag_own_car.FLAG_OWN_CAR_ID

  LEFT JOIN dim_flag_own_realty ON df.FLAG_OWN_REALTY_ID = dim_flag_own_realty.FLAG_OWN_REALTY_ID

  LEFT JOIN dim_name_type_suite ON df.NAME_TYPE_SUITE_ID = dim_name_type_suite.NAME_TYPE_SUITE_ID

  LEFT JOIN dim_name_income_type ON df.NAME_INCOME_TYPE_ID = dim_name_income_type.NAME_INCOME_TYPE_ID

  LEFT JOIN dim_name_education_type ON df.NAME_EDUCATION_TYPE_ID = dim_name_education_type.NAME_EDUCATION_TYPE_ID

  LEFT JOIN dim_name_family_status ON df.NAME_FAMILY_STATUS_ID = dim_name_family_status.NAME_FAMILY_STATUS_ID

  LEFT JOIN dim_name_housing_type ON df.NAME_HOUSING_TYPE_ID = dim_name_housing_type.NAME_HOUSING_TYPE_ID

  LEFT JOIN dim_occupation_type ON df.OCCUPATION_TYPE_ID = dim_occupation_type.OCCUPATION_TYPE_ID

  LEFT JOIN dim_weekday_appr_process_start ON df.WEEKDAY_APPR_PROCESS_START_ID = dim_weekday_appr_process_start.WEEKDAY_APPR_PROCESS_START_ID

  LEFT JOIN dim_organization_type ON df.ORGANIZATION_TYPE_ID = dim_organization_type.ORGANIZATION_TYPE_ID

  LEFT JOIN dim_fondkapremont_mode ON df.FONDKAPREMONT_MODE_ID = dim_fondkapremont_mode.FONDKAPREMONT_MODE_ID

  LEFT JOIN dim_housetype_mode ON df.HOUSETYPE_MODE_ID = dim_housetype_mode.HOUSETYPE_MODE_ID

  LEFT JOIN dim_wallsmaterial_mode ON df.WALLSMATERIAL_MODE_ID = dim_wallsmaterial_mode.WALLSMATERIAL_MODE_ID

  LEFT JOIN dim_emergencystate_mode ON df.EMERGENCYSTATE_MODE_ID = dim_emergencystate_mode.EMERGENCYSTATE_MODE_ID

  LEFT JOIN dim_organization_type_2 ON df.ORGANIZATION_TYPE_2_ID = dim_organization_type_2.ORGANIZATION_TYPE_2_ID

In [39]:
# Control de join de tablas descompuestas.

# Construcción de diccionario con dataframe principal y dataframes de dimensiones.
env = {**dimension_tables, 'df': df}

# Ejecución de la query.
control_df = sqldf(query, env) # sqldf(query, locals())
control_df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,ORGANIZATION_TYPE_2
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,Type 3
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Type 0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Type 0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,Type 3
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,Type 0

In [40]:
# Shape de control_df.
control_df.shape

(307511, 123)

In [41]:
# Reemplazo de NoneType por np.nans.
for col in control_df.columns:
    # Verificacion si 'None' (NoneType) está presente en la columna.
    if control_df[col].apply(lambda x: x is None).any():
        control_df[col] = control_df[col].replace({None: np.nan})

print("Valores None fueron reemplazados con np.nan para todas las columnas de control_df.")

Valores None fueron reemplazados con np.nan para todas las columnas de control_df.

In [42]:
# Cotejo final de control_df con df_backup.

matching_counts = {}

# Asegurar que solo comparamos las columnas que existen en ambos DataFrames.
columns_to_compare = [col for col in df_backup.columns if col in control_df.columns]

for col in columns_to_compare:
    s1 = control_df[col]
    s2 = df_backup[col]

    # Comparar valores, tratando np.nan como iguales si ambos lo son
    # Esto gestiona tanto valores iguales no nulos (s1 == s2) como coincidencias NaN-NaN (s1.isna() & s2.isna())
    matches = ((s1 == s2) | (s1.isna() & s2.isna()))
    matching_counts[col] = matches.sum()

# Crear un DataFrame para visualizar mejor los resultados
comparison_df = pd.DataFrame(matching_counts.items(), columns=['Column', 'Matching_Count'])
comparison_df['Total_Rows'] = len(df_backup)
comparison_df['Percentage_Match'] = (comparison_df['Matching_Count'] / comparison_df['Total_Rows']) * 100

display(comparison_df)

# Opcionalmente, mostrar columnas que no tienen un 100% de coincidencia para facilitar la inspección
non_full_match_cols = comparison_df[comparison_df['Percentage_Match'] < 100]
if not non_full_match_cols.empty:
    print("\nColumnas con menos del 100% de coincidencia (debido a diferencias reales de valores, no solo manejo de NaN):")
    display(non_full_match_cols)
else:
    print("\nTodas las columnas comparadas tienen una coincidencia del 100% (incluyendo la igualdad NaN-NaN).")

                         Column  Matching_Count  Total_Rows  Percentage_Match
0                    SK_ID_CURR          307511      307511             100.0
1                        TARGET          307511      307511             100.0
2            NAME_CONTRACT_TYPE          307511      307511             100.0
3                   CODE_GENDER          307511      307511             100.0
4                  FLAG_OWN_CAR          307511      307511             100.0
..                          ...             ...         ...               ...
118  AMT_REQ_CREDIT_BUREAU_WEEK          307511      307511             100.0
119   AMT_REQ_CREDIT_BUREAU_MON          307511      307511             100.0
120   AMT_REQ_CREDIT_BUREAU_QRT          307511      307511             100.0
121  AMT_REQ_CREDIT_BUREAU_YEAR          307511      307511             100.0
122         ORGANIZATION_TYPE_2          307511      307511             100.0

[123 rows x 4 columns]

Todas las columnas comparadas tienen una coincidencia del 100% (incluyendo la igualdad NaN-NaN).

### Exportación de DataFrames a CSV

Este paso guarda el DataFrame principal y cada una de las tablas de dimensiones creadas en archivos CSV individuales. Esto permite un almacenamiento y uso posterior más sencillo de los datos normalizados y las tablas de referencia.

In [43]:
# Creacion de directorio output.
ref_name = csv_name.replace('.csv', '')
extract_dir = output_dir + ref_name + '/'

# Evaluacion de existencia del directorio.
if not os.path.exists(extract_dir):
    os.makedirs(extract_dir)

# Guardar el dataFrame principal 'df' en un archivo CSV.
df.to_csv(extract_dir + csv_name, index=False)
print(f'DataFrame principal guardado como {csv_name}')

# Guardar cada tabla de dimensiones en un archivo CSV separado
for name, dim_df in dimension_tables.items():
    file_name = f'{name}.csv'
    dim_df.to_csv(extract_dir + file_name, index=False)
    print(f'Tabla de dimensiones "{name}" guardada como {file_name}')

DataFrame principal guardado como application_train.csv
Tabla de dimensiones "dim_name_contract_type" guardada como dim_name_contract_type.csv
Tabla de dimensiones "dim_code_gender" guardada como dim_code_gender.csv
Tabla de dimensiones "dim_flag_own_car" guardada como dim_flag_own_car.csv
Tabla de dimensiones "dim_flag_own_realty" guardada como dim_flag_own_realty.csv
Tabla de dimensiones "dim_name_type_suite" guardada como dim_name_type_suite.csv
Tabla de dimensiones "dim_name_income_type" guardada como dim_name_income_type.csv
Tabla de dimensiones "dim_name_education_type" guardada como dim_name_education_type.csv
Tabla de dimensiones "dim_name_family_status" guardada como dim_name_family_status.csv
Tabla de dimensiones "dim_name_housing_type" guardada como dim_name_housing_type.csv
Tabla de dimensiones "dim_occupation_type" guardada como dim_occupation_type.csv
Tabla de dimensiones "dim_weekday_appr_process_start" guardada como dim_weekday_appr_process_start.csv
Tabla de dimensiones "dim_organization_type" guardada como dim_organization_type.csv
Tabla de dimensiones "dim_fondkapremont_mode" guardada como dim_fondkapremont_mode.csv
Tabla de dimensiones "dim_housetype_mode" guardada como dim_housetype_mode.csv
Tabla de dimensiones "dim_wallsmaterial_mode" guardada como dim_wallsmaterial_mode.csv
Tabla de dimensiones "dim_emergencystate_mode" guardada como dim_emergencystate_mode.csv
Tabla de dimensiones "dim_organization_type_2" guardada como dim_organization_type_2.csv

# bureau_balance

### Analisis de datos preliminar

In [44]:
# Lectura del dataset.
csv_name = 'bureau_balance.csv'
df = pd.read_csv(data_path + csv_name)

# Head del dataset.
df.info()

# Head del dataset.
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27299925 entries, 0 to 27299924
Data columns (total 3 columns):
 #   Column          Dtype
---  ------          -----
 0   SK_ID_BUREAU    int64
 1   MONTHS_BALANCE  int64
 2   STATUS          object
dtypes: int64(2), object(1)
memory usage: 624.8+ MB

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

In [45]:
# Obtención de valores únicos para atributos categóricos y numéricos no float.
for column in df.columns:
    unique_values = df[column].unique()

    # Indicador para verificar si la columna contiene algún valor float no entero (excluyendo NaN)
    contains_non_integer_float = False

    # Iterar sobre los valores únicos para encontrar floats no enteros
    for val in unique_values:
        # Verificar si el valor es un float y no es NaN
        if isinstance(val, float) and not np.isnan(val):
            # Verificar si el float tiene una parte decimal distinta de cero
            if val != int(val):
                contains_non_integer_float = True
                break  # Se encontró un float no entero, no es necesario seguir verificando

    # Si no se encontró ningún float no entero, imprimir los valores únicos de la columna
    if not contains_non_integer_float:
        print(f"Columna '{column}':{unique_values}")

Columna 'SK_ID_BUREAU':[5715448 5715449 5715451 ... 5041172 5041332 5041336]
Columna 'MONTHS_BALANCE':[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17
 -18 -19 -20 -21 -22 -23 -24 -25 -26 -27 -28 -29 -30 -31 -32 -33 -34 -35
 -36 -37 -38 -39 -40 -41 -42 -43 -44 -45 -46 -47 -48 -49 -50 -51 -52 -53
 -54 -55 -56 -57 -58 -59 -60 -61 -62 -63 -64 -65 -66 -67 -68 -69 -70 -71
 -72 -73 -74 -75 -76 -77 -78 -79 -80 -81 -82 -83 -84 -85 -86 -87 -88 -89
 -90 -91 -92 -93 -94 -95 -96]
Columna 'STATUS':['C' '0' 'X' '1' '2' '3' '5' '4']

In [46]:
# Obtención de valores únicos para atributos categóricos.
for column in df.columns:
    # Evaluación si el tipo es string.
    if df[column].dtype == 'object':
        unique_values = df[column].unique()
        print(f"Columna '{column}': {unique_values}")

Columna 'STATUS': ['C' '0' 'X' '1' '2' '3' '5' '4']

### Mejoras de diseño

Dado que un sólo atributo es optimizable, se mantienen los datos en la tabla en el mismo estado en que se encuentran.

# bureau

### Analisis de datos preliminar

In [47]:
# Lectura del dataset.
csv_name = 'bureau.csv'
df = pd.read_csv(data_path + csv_name)

# Head del dataset.
df.info()

# Head del dataset.
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1716428 entries, 0 to 1716427
Data columns (total 17 columns):
 #   Column                  Dtype
---  ------                  -----
 0   SK_ID_CURR              int64
 1   SK_ID_BUREAU            int64
 2   CREDIT_ACTIVE           object
 3   CREDIT_CURRENCY         object
 4   DAYS_CREDIT             int64
 5   CREDIT_DAY_OVERDUE      int64
 6   DAYS_CREDIT_ENDDATE     float64
 7   DAYS_ENDDATE_FACT       float64
 8   AMT_CREDIT_MAX_OVERDUE  float64
 9   CNT_CREDIT_PROLONG      int64
 10  AMT_CREDIT_SUM          float64
 11  AMT_CREDIT_SUM_DEBT     float64
 12  AMT_CREDIT_SUM_LIMIT    float64
 13  AMT_CREDIT_SUM_OVERDUE  float64
 14  CREDIT_TYPE             object
 15  DAYS_CREDIT_UPDATE      int64
 16  AMT_ANNUITY             float64
dtypes: float64(8), int64(6), object(3)
memory usage: 222.6+ MB

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [48]:
# Obtención de valores únicos para atributos categóricos y numéricos no float.
for column in df.columns:
    unique_values = df[column].unique()

    # Indicador para verificar si la columna contiene algún valor float no entero (excluyendo NaN)
    contains_non_integer_float = False

    # Iterar sobre los valores únicos para encontrar floats no enteros
    for val in unique_values:
        # Verificar si el valor es un float y no es NaN
        if isinstance(val, float) and not np.isnan(val):
            # Verificar si el float tiene una parte decimal distinta de cero
            if val != int(val):
                contains_non_integer_float = True
                break  # Se encontró un float no entero, no es necesario seguir verificando

    # Si no se encontró ningún float no entero, imprimir los valores únicos de la columna
    if not contains_non_integer_float:
        print(f"Columna '{column}':{unique_values}")

Columna 'SK_ID_CURR':[215354 162297 402440 ... 448157 345866 235871]
Columna 'SK_ID_BUREAU':[5714462 5714463 5714464 ... 5057762 5057770 5057778]
Columna 'CREDIT_ACTIVE':['Closed' 'Active' 'Sold' 'Bad debt']
Columna 'CREDIT_CURRENCY':['currency 1' 'currency 2' 'currency 4' 'currency 3']
Columna 'DAYS_CREDIT':[-497 -208 -203 ...    0   -3   -1]
Columna 'CREDIT_DAY_OVERDUE':[   0 2603    6   30 2156  496  186 2264   41    8   71   13  252 1201
   12   38 1777  150   18   37   64 2050    9    4   29   22   49 1930
   34  951  936  664   45 2625  837   21   15   31 1715   19   67    7
   26   23   48   46   73   90 1127   53   33 1572   39 2582   14   25
   10   50   17  193   40   20   28  123  138  700  122 1504   32  670
   75  140   24  277 2019  161  962  187   58  106  634   83  120   60
   93 1694  227   44  344 2085 1248  124 1651 2541 1541  642  745  163
  234 1472  688 2455  614  319 2187   68  831  139  283  180   47  164
  174 1604 1326 2149   36   62  753  374 1573 1562 2400   35  860   11
  776  520   77 1892 1786   80 2310 2383  136  264  131    5 2571 1579
  198 2534 2292   63   72 2238 1475 2614  107    3 1195  990 1430  242
  249   16  648  659  100 2210 2249   57  672 2765   52 1899  676   43
   27  288   69 1222 2246  108  149 1087  212  256  192  211 2476  144
  141  650  110  372  948  651 1674 2188   76 2620   82  117 1428 2481
  104  216   91  618  635 2133 1409  226 1903 2592  338  155 2041   42
   54  143 1632  625  132  225  890  165  241 1747   78  719 1760  152
 1714  363 1406 1032 1307   66  477 1058   88  621 2463   81 1501  669
 1727  102   84  103  418  586 2364 2693 1272 2524 2030 1729 2069  171
 1417 2527  668 2129    2 2537  175  199  356   56 1761 1704  433   61
  209  652 1769 1455  893  183 1142 1172 1695  126 1319  817 1077 1862
 1601 1482 1018 2349 2312 1100   99 1620   98   55   59 2442  646 2499
  865 2234   51 2331 1150 1179   79 1072  819  480 2384   85  895 1062
  245 1554  127 1796 1506    1  114 2141   86 2195  237  592  388 2640
 2610 2282 1982  397 1118  458 1097  159 2544  952 1973   97 1591 1650
  653 1678  172 1529 2586  612  879  101 1240 1038 1587  157 1381 1088
  691 2602  345  748 1881 1474  986  208 1000  639 1403  640  328 2270
   65  128  276 2078  846  907  632 1452 2638  686 1036   74 1244  552
 1774 1763 2700  870  204 2456  177 2580  610  638   87  210  943 1927
 2184 2165  671 1733 2685 2243 2585 2466 2254 1590  195 2397 2595   94
  677  666  105  235  366  273  142 2770 2679 2379  445  724 2121 1921
 1814  221  403  243 2137  296 1011 1637  991 1829 1162 1684 1857  364
 2317  334  285  588  649  224 1499 1680  689 1512 2644  981 1997  213
 1826 2542 1570  219  244  611 1445  188  278  707 2193  179 2299 1919
 2092 1770 2599 2340  166 1275 1540 1469 2354 1671  169 2348 1233  752
  160  493 1047 1845 1206  738 1943 2347 2473  718 2629 2134  872 2168
 2080  268 2781   95  547 1835  115   70 2598  730 1681 2703 2324 2289
  190 2028 1618   89 2581  153 1764 2609 2395 2529 2652  135  414  206
  953  605 2108 1719 2565 2623  147  932 2754 1232 1178 2138 1199 2574
   92  238 1001  312  214 1468  934 2657  337 2279 1074  519 1075  641
  473  341  321 1051 2286 1226 1338 2275  960 1061  158  373  673 2391
 2221  429 2018  130 1993 2034 2358  112  326 2484 2616 1947 1742 1631
 1629  544 1463 1073 2048 1049  220  643  615  154  423 2217 1682 1131
 1086 2553  606 2071 2684  761 1009  358 2440  476 2513  232  630 1055
  133 1667  113 1875  441  768  181 1397 2332 1737 1290  148 1635  680
  714 1325 1521 1522 2059 1724 1313 1740 2277 1352  994 1104 2776 2211
 1042 2325 2600  426 2552  877 1670 1711  733  119 2656 2360 1235 1093
 1031 1197 2290  920 1887 1530 2117 2591  927  265  737 2464 1644  685
  723 2677 2588  647  631 1350  325  550 2212  756 1939 1167  362  251
 2058  891  781 1502 1205  931  944  121  525 1116 1068  747  472 1285
  452  619 2164  368 1524 2214 1907 1759  280 1274  969 1363 2335  303
 1936 1247 1552 1177  938  261  910  170  996 1252  827 1736  679  982
  731  720  674  919 1388  717 2029 2631 2502 2298  830 1638  146 2649
  915  247  806 1634 2252 1200 1218 1408  413 2295 2667  537  616 1364
  422 2353 2066  599  656 2474 2637  437 2643 2201 2175  289 1189 2661
  109 2338 1776  348 2102 2053  314  974  985  292 2099  810 1813 1334
 1095  137 1489  125 1253 1548  502  848 2258 1720 1804 1299  455 1194
  189  929 1706  584  942 1420 1213  134  290  269 2272  657 1766  217
 2128  408 1822 2627  593  129  231  178 1020  191 2577  485 1961  406
 1503 1703 2057 2641  795 1901 2093 1752  320  317 1255 1523 2228  933
 2766 1612  995  162 1843  694 2176  168 1648 2606 1209 1505  514 1797
  116 2546 2146  504 1755 1692 1722  200   96 2157  531 1962 1480  743
 2688 1588 1402  284  440  678 2280 1171  629  467 1135  786  976 1393
 2545 1161 2394 1404  176 2220 1183 2497 1972  873  299  787 1156  118
 1739 1060 2426 2604 2792  883 2355 2061 1584  465 1556 2301  275 1859
  184 1546  687  439 2634 2540  291 1496 1514 1193 2639 2608 2651 1754
 1918 1858 1298  554  876  323 2528 2681 2496 2109  324  765 2256 1278
 2284 2536 1693 1398 1912  826 2107  167  515  407 1863  460 1158  727
 1610 2204 2654 1931]
Columna 'DAYS_CREDIT_ENDDATE':[-153. 1075.  528. ... 5922. 3835. 5650.]
Columna 'DAYS_ENDDATE_FACT':[ -153.    nan -1710. ... -2919. -3042. -2891.]
Columna 'CNT_CREDIT_PROLONG':[0 2 1 4 3 5 9 8 6 7]
Columna 'CREDIT_TYPE':['Consumer credit' 'Credit card' 'Mortgage' 'Car loan' 'Microloan'
 'Loan for working capital replenishment' 'Loan for business development'
 'Real estate loan' 'Unknown type of loan' 'Another type of loan'
 'Cash loan (non-earmarked)' 'Loan for the purchase of equipment'
 'Mobile operator loan' 'Interbank credit'
 'Loan for purchase of shares (margin lending)']
Columna 'DAYS_CREDIT_UPDATE':[  -131    -20    -16 ...  -2901 -41918  -2844]

In [49]:
# Obtención de valores únicos para atributos categóricos.
for column in df.columns:
    # Evaluación si el tipo es string.
    if df[column].dtype == 'object':
        unique_values = df[column].unique()
        print(f"Columna '{column}': {unique_values}")

Columna 'CREDIT_ACTIVE': ['Closed' 'Active' 'Sold' 'Bad debt']
Columna 'CREDIT_CURRENCY': ['currency 1' 'currency 2' 'currency 4' 'currency 3']
Columna 'CREDIT_TYPE': ['Consumer credit' 'Credit card' 'Mortgage' 'Car loan' 'Microloan'
 'Loan for working capital replenishment' 'Loan for business development'
 'Real estate loan' 'Unknown type of loan' 'Another type of loan'
 'Cash loan (non-earmarked)' 'Loan for the purchase of equipment'
 'Mobile operator loan' 'Interbank credit'
 'Loan for purchase of shares (margin lending)']

### Mejoras de diseño

In [50]:
# Creación de copia para control posterior.
df_backup = df.copy()

In [51]:
# Obtención de atributos categoricos.
dimension_tables = {}
categorical_columns = [col for col in df.columns if df[col].dtype == 'object']

In [52]:
# Creación de tablas de dimensiones.
for col in categorical_columns:
    # Extraer valores únicos no NaN para la tabla de dimensión
    unique_values = df[col].dropna().unique()

    if len(unique_values) > 0:
        # Crear una tabla de dimensión para la columna categórica actual
        dim_df = pd.DataFrame({
            f'{col}_ID': range(1, len(unique_values) + 1),
            col: unique_values
        })
        dimension_tables[f'dim_{col.lower()}'] = dim_df

        # Crear un mapeo desde el valor original al nuevo ID, manejando NaN
        mapping = dict(zip(dim_df[col], dim_df[f'{col}_ID']))

        # Reemplazar los valores categóricos en el DataFrame original con sus IDs
        # Usar .map() que maneja valores NaN por defecto, preservándolos si no están en el mapeo
        df[col] = df[col].map(mapping)

        # Renombrar la columna para reflejar que ahora contiene IDs
        df.rename(columns={col: f'{col}_ID'}, inplace=True)
    else:
        print(f"La columna '{col}' no tiene valores únicos que no estén vacios, por lo tanto se omite la creación de la tabla de dimensión.")

In [53]:
# Control de atributos.
print(f'Recuento de columnas categoricas: {len(categorical_columns)}')
print(f'Recuento de tablas de dimensiones: {len(dimension_tables)}')

Recuento de columnas categoricas: 3
Recuento de tablas de dimensiones: 3

In [54]:
# Tablas de dimensiones.
print(f'Tablas de dimensiones: {[*dimension_tables.keys()]}')

Tablas de dimensiones: ['dim_credit_active', 'dim_credit_currency', 'dim_credit_type']

In [55]:
# Print de atributos del dataset backup.
print(f'Columnas del dataset de referencia: {[*df_backup.columns]}')

Columnas del dataset de referencia: ['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE', 'CREDIT_CURRENCY', 'DAYS_CREDIT', 'CREDIT_DAY_OVERDUE', 'DAYS_CREDIT_ENDDATE', 'DAYS_ENDDATE_FACT', 'AMT_CREDIT_MAX_OVERDUE', 'CNT_CREDIT_PROLONG', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM_OVERDUE', 'CREDIT_TYPE', 'DAYS_CREDIT_UPDATE', 'AMT_ANNUITY']

In [56]:
# Query para la verificación del join de tablas principal y de dimensiones.
query = f"""
SELECT {', '.join(df_backup.columns)}
FROM df
"""

dim_tables_names = [*dimension_tables.keys()]

for dim_table_name in dim_tables_names:
  dim_table_id = dimension_tables[dim_table_name].columns[0]

  query += f"""
  LEFT JOIN {dim_table_name} ON df.{dim_table_id} = {dim_table_name}.{dim_table_id}
  """

In [57]:
# Impresion de la query.
print(query)

SELECT SK_ID_CURR, SK_ID_BUREAU, CREDIT_ACTIVE, CREDIT_CURRENCY, DAYS_CREDIT, CREDIT_DAY_OVERDUE, DAYS_CREDIT_ENDDATE, DAYS_ENDDATE_FACT, AMT_CREDIT_MAX_OVERDUE, CNT_CREDIT_PROLONG, AMT_CREDIT_SUM, AMT_CREDIT_SUM_DEBT, AMT_CREDIT_SUM_LIMIT, AMT_CREDIT_SUM_OVERDUE, CREDIT_TYPE, DAYS_CREDIT_UPDATE, AMT_ANNUITY
FROM df

  LEFT JOIN dim_credit_active ON df.CREDIT_ACTIVE_ID = dim_credit_active.CREDIT_ACTIVE_ID

  LEFT JOIN dim_credit_currency ON df.CREDIT_CURRENCY_ID = dim_credit_currency.CREDIT_CURRENCY_ID

  LEFT JOIN dim_credit_type ON df.CREDIT_TYPE_ID = dim_credit_type.CREDIT_TYPE_ID

In [58]:
# Control de join de tablas descompuestas.

# Construcción de diccionario con dataframe principal y dataframes de dimensiones.
env = {**dimension_tables, 'df': df}

# Ejecución de la query.
control_df = sqldf(query, env) # sqldf(query, locals())
control_df.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [59]:
# Shape de control_df.
control_df.shape

(1716428, 17)

In [60]:
# Reemplazo de NoneType por np.nans.
for col in control_df.columns:
    # Verificacion si 'None' (NoneType) está presente en la columna.
    if control_df[col].apply(lambda x: x is None).any():
        control_df[col] = control_df[col].replace({None: np.nan})

print("Valores None fueron reemplazados con np.nan para todas las columnas de control_df.")

Valores None fueron reemplazados con np.nan para todas las columnas de control_df.

In [61]:
# Cotejo final de control_df con df_backup.

matching_counts = {}

# Asegurar que solo comparamos las columnas que existen en ambos DataFrames.
columns_to_compare = [col for col in df_backup.columns if col in control_df.columns]

for col in columns_to_compare:
    s1 = control_df[col]
    s2 = df_backup[col]

    # Comparar valores, tratando np.nan como iguales si ambos lo son
    # Esto gestiona tanto valores iguales no nulos (s1 == s2) como coincidencias NaN-NaN (s1.isna() & s2.isna())
    matches = ((s1 == s2) | (s1.isna() & s2.isna()))
    matching_counts[col] = matches.sum()

# Crear un DataFrame para visualizar mejor los resultados
comparison_df = pd.DataFrame(matching_counts.items(), columns=['Column', 'Matching_Count'])
comparison_df['Total_Rows'] = len(df_backup)
comparison_df['Percentage_Match'] = (comparison_df['Matching_Count'] / comparison_df['Total_Rows']) * 100

display(comparison_df)

# Opcionalmente, mostrar columnas que no tienen un 100% de coincidencia para facilitar la inspección
non_full_match_cols = comparison_df[comparison_df['Percentage_Match'] < 100]
if not non_full_match_cols.empty:
    print("\nColumnas con menos del 100% de coincidencia (debido a diferencias reales de valores, no solo manejo de NaN):")
    display(non_full_match_cols)
else:
    print("\nTodas las columnas comparadas tienen una coincidencia del 100% (incluyendo la igualdad NaN-NaN).")

                    Column  Matching_Count  Total_Rows  Percentage_Match
0               SK_ID_CURR         1716428     1716428             100.0
1             SK_ID_BUREAU         1716428     1716428             100.0
2            CREDIT_ACTIVE         1716428     1716428             100.0
3          CREDIT_CURRENCY         1716428     1716428             100.0
4              DAYS_CREDIT         1716428     1716428             100.0
5       CREDIT_DAY_OVERDUE         1716428     1716428             100.0
6      DAYS_CREDIT_ENDDATE         1716428     1716428             100.0
7        DAYS_ENDDATE_FACT         1716428     1716428             100.0
8   AMT_CREDIT_MAX_OVERDUE         1716428     1716428             100.0
9       CNT_CREDIT_PROLONG         1716428     1716428             100.0
10          AMT_CREDIT_SUM         1716428     1716428             100.0
11     AMT_CREDIT_SUM_DEBT         1716428     1716428             100.0
12    AMT_CREDIT_SUM_LIMIT         1716428     1716428             100.0
13  AMT_CREDIT_SUM_OVERDUE         1716428     1716428             100.0
14             CREDIT_TYPE         1716428     1716428             100.0
15      DAYS_CREDIT_UPDATE         1716428     1716428             100.0
16             AMT_ANNUITY         1716428     1716428             100.0

Todas las columnas comparadas tienen una coincidencia del 100% (incluyendo la igualdad NaN-NaN).

### Exportación de DataFrames a CSV

Este paso guarda el DataFrame principal y cada una de las tablas de dimensiones creadas en archivos CSV individuales. Esto permite un almacenamiento y uso posterior más sencillo de los datos normalizados y las tablas de referencia.

In [62]:
# Creacion de directorio output.
ref_name = csv_name.replace('.csv', '')
extract_dir = output_dir + ref_name + '/'

# Evaluacion de existencia del directorio.
if not os.path.exists(extract_dir):
    os.makedirs(extract_dir)

# Guardar el dataFrame principal 'df' en un archivo CSV.
df.to_csv(extract_dir + csv_name, index=False)
print(f'DataFrame principal guardado como {csv_name}')

# Guardar cada tabla de dimensiones en un archivo CSV separado
for name, dim_df in dimension_tables.items():
    file_name = f'{name}.csv'
    dim_df.to_csv(extract_dir + file_name, index=False)
    print(f'Tabla de dimensiones "{name}" guardada como {file_name}')

DataFrame principal guardado como bureau.csv
Tabla de dimensiones "dim_credit_active" guardada como dim_credit_active.csv
Tabla de dimensiones "dim_credit_currency" guardada como dim_credit_currency.csv
Tabla de dimensiones "dim_credit_type" guardada como dim_credit_type.csv

# credit_card_balance

### Analisis de datos preliminar

In [63]:
# Lectura del dataset.
csv_name = 'credit_card_balance.csv'
df = pd.read_csv(data_path + csv_name)

# Head del dataset.
df.info()

# Head del dataset.
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3840312 entries, 0 to 3840311
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   SK_ID_PREV                  int64
 1   SK_ID_CURR                  int64
 2   MONTHS_BALANCE              int64
 3   AMT_BALANCE                 float64
 4   AMT_CREDIT_LIMIT_ACTUAL     int64
 5   AMT_DRAWINGS_ATM_CURRENT    float64
 6   AMT_DRAWINGS_CURRENT        float64
 7   AMT_DRAWINGS_OTHER_CURRENT  float64
 8   AMT_DRAWINGS_POS_CURRENT    float64
 9   AMT_INST_MIN_REGULARITY     float64
 10  AMT_PAYMENT_CURRENT         float64
 11  AMT_PAYMENT_TOTAL_CURRENT   float64
 12  AMT_RECEIVABLE_PRINCIPAL    float64
 13  AMT_RECIVABLE               float64
 14  AMT_TOTAL_RECEIVABLE        float64
 15  CNT_DRAWINGS_ATM_CURRENT    float64
 16  CNT_DRAWINGS_CURRENT        int64
 17  CNT_DRAWINGS_OTHER_CURRENT  float64
 18  CNT_DRAWINGS_POS_CURRENT    float64
 19  CNT_INSTALMENT_MATURE_CUM   float64
 20  NAME_CONTRACT_STATUS        object
 21  SK_DPD                      int64
 22  SK_DPD_DEF                  int64
dtypes: float64(15), int64(7), object(1)
memory usage: 673.9+ MB

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0

In [64]:
# Obtención de valores únicos para atributos categóricos y numéricos no float.
for column in df.columns:
    unique_values = df[column].unique()

    # Indicador para verificar si la columna contiene algún valor float no entero (excluyendo NaN)
    contains_non_integer_float = False

    # Iterar sobre los valores únicos para encontrar floats no enteros
    for val in unique_values:
        # Verificar si el valor es un float y no es NaN
        if isinstance(val, float) and not np.isnan(val):
            # Verificar si el float tiene una parte decimal distinta de cero
            if val != int(val):
                contains_non_integer_float = True
                break  # Se encontró un float no entero, no es necesario seguir verificando

    # Si no se encontró ningún float no entero, imprimir los valores únicos de la columna
    if not contains_non_integer_float:
        print(f"Columna '{column}':{unique_values}")

Columna 'SK_ID_PREV':[2562384 2582071 1740877 ... 1897864 2481982 2191610]
Columna 'SK_ID_CURR':[378907 363914 371185 ... 174455 315041 382749]
Columna 'MONTHS_BALANCE':[ -6  -1  -7  -4  -5  -3  -2 -19 -13 -18 -15 -12 -22 -16 -21 -14 -20 -17
 -11 -52 -54 -58 -53 -51 -50 -59 -56 -57 -60 -55 -26 -25 -24 -23 -67 -64
 -62 -63 -61 -65 -66 -10  -9 -88 -95 -86 -89 -91 -93 -87 -90 -92 -94 -85
 -72 -73 -70 -69 -68 -71 -74  -8 -27 -80 -79 -84 -83 -81 -82 -96 -28 -36
 -31 -32 -40 -41 -35 -34 -39 -33 -37 -38 -47 -48 -45 -44 -43 -49 -42 -46
 -76 -78 -77 -75 -30 -29]
Columna 'AMT_CREDIT_LIMIT_ACTUAL':[ 135000   45000  450000  225000  270000  585000  292500  180000   67500
       0  157500  360000  540000  558000  202500  247500  112500   90000
  720000  315000  900000   22500  675000  855000  382500  495000  337500
  765000  405000  108000  630000  810000  427500  261000  229500   27000
   81000  216000  103500   58500  468000  342000   94500  274500  234000
  130500  400500    4500   36000  306000 1125000   72000   54000   63000
  162000    9000   40500   13500   49500  193500   18000   76500  166500
  756000  265500  828000  256500  126000  175500  657000  288000  171000
  144000  490500   31500  580500  391500  211500  139500  445500  409500
  432000  324000  198000  396000  121500  414000  436500  220500  333000
  207000  148500  373500  387000  243000  423000  252000  418500  513000
  301500  279000  328500 1350000   99000   85500  346500  837000  351000
  441000  153000  310500  189000  378000  319500  364500  117000  661500
  283500  508500  477000  369000  238500  760500  553500  621000  567000
  454500  738000  184500  616500  571500  783000  697500  486000  751500
  535500  594000  522000  297000  891000 1237500  562500  706500  531000
  742500  702000  472500 1012500  774000  355500  864000  792000  463500
  544500  612000  747000  481500  715500  589500  459000  648000  670500
  504000  729000  679500  576000  693000  526500  499500  684000  643500
  607500  549000  819000  652500  688500  711000  598500  634500  666000
  625500]
Columna 'CNT_DRAWINGS_ATM_CURRENT':[ 0.  1.  3.  5.  2. nan  6. 13.  4.  8.  9.  7. 10. 12. 11. 18. 19. 14.
 15. 16. 33. 17. 20. 29. 22. 24. 21. 31. 23. 28. 25. 30. 27. 26. 44. 35.
 36. 34. 39. 51. 38. 41. 43. 32. 37.]
Columna 'CNT_DRAWINGS_CURRENT':[  1   0   8   9   5   2  30   3   4   7  14  38  12  19  26  17  33   6
  15  10 101  72  32  53  20  16  23  47  28  43  22  49  13  75  24  18
  11  39  25  21  29  77  69  36  34  48  35  27  44  31  40  59  80  51
  41  37  42  57  64  56  60  88  54  63  50  78 108  55  46  62  85  71
  94  73  58  70  82  45  74  96  83 124 142  52  95  84  61  92  76  68
  90  79  91  66  81  67 135  99  65 104  86 106 112  97  93  87 162 105
 107 119  89 114 103 102 126 116 111 165 143 120 151 117 118 109 130 136
 121 100  98]
Columna 'CNT_DRAWINGS_OTHER_CURRENT':[ 0.  1. nan  3.  2.  4.  6.  5.  7.  8. 10. 12.]
Columna 'CNT_DRAWINGS_POS_CURRENT':[  1.   0.   5.   6.  29.   4.   8.   2.  nan  14.  38.  12.   3.  17.
  26.   7.  30.  15.   9.  10. 101.  72.  32.  53.  20.  16.  23.  47.
  11.  28.  43.  49.  22.  13.  75.  24.  33.  18.  19.  39.  25.  21.
  77.  69.  36.  34.  48.  35.  27.  44.  31.  40.  57.  51.  37.  42.
  41.  63.  60.  85.  54.  50.  46.  78.  56. 108.  55.  45.  62.  64.
  71.  66.  94.  58.  70.  82.  74.  73.  96.  52. 115. 142.  95.  59.
  84.  61.  92.  76.  65.  90.  79.  89.  81.  67. 135.  80.  91. 104.
  86.  99. 105. 112.  83.  93.  68.  87. 162.  97.  88. 107. 124. 119.
 114. 102. 103. 126. 118. 116. 111. 165. 110. 143. 140. 120. 106. 151.
 117. 109. 130. 136. 121. 123.  98. 100.]
Columna 'CNT_INSTALMENT_MATURE_CUM':[ 35.  69.  30.  10. 101.   2.   6.  51.   3.  38.   0.  27.  59.  11.
  42.  33.  22.  16.   5.  25.  70.   1.  80.  92.  13.  26.   4.  21.
  95.  85.  15.  54.   8.  12.   7.  39.   9.  40.  45.  28.  20.  49.
  53.  18.  79.  76.  65.  82.  55.  32.  43.  24.  29.  73.  58.  41.
  72.  46.  14.  23.  17.  88.  64.  47.  31.  52.  19.  56.  78.  61.
 104.  34.  50.  44.  83.  37.  77.  67.  68.  96.  63.  91. 103.  66.
  94.  81.  36.  97.  90. 102.  87. 106.  71.  93. 111.  74.  48.  60.
  89. 116.  75. 100.  57.  99.  62.  98. 108. 112. 107.  84.  86.  nan
 105. 110. 115. 109. 113. 114. 117. 118. 120. 119.]
Columna 'NAME_CONTRACT_STATUS':['Active' 'Completed' 'Demand' 'Signed' 'Sent proposal' 'Refused'
 'Approved']
Columna 'SK_DPD':[   0    7 2192  717   28   18 1676 1706 1311 1158 1462   99 1341 1645
  270 1127   68 1188  641 1827   58  396 1097 1280    1  150 1066 1400
 2102  822 1128    8   92  151  974   62  123  213  274  182  243  639
 1765 1309  575  821  332  427  518  640  335  158  701  121  609   32
  154   49  794 1135 1524 1373  424 1403 1226 1434   59 1493  642 1585
 1038 1250  854   91    5  200  762  216   63  731  489  823  338  672
   39  793  277  703  550  702   93 1553   42  761  574   31   38 1857
 1584  366 1612  852  138 1005  913 1248 1492 1217  152  883 1007 1279
  244  336  425  397  275  517  456  578  487  882  548  670 1554   69
  250 1189 1278 1219  667 1339  153  122   90 1766 1432 1615 1036  763
 1401 1281 1159 1067 1707 1646  305   60  185  610  276   29 1738  283
 1342 1340 1735 1613 2284 1674 2162 1582  120   79 1643  700   12   57
 1370  975   61   30  189   87  307  252  183  140  245  246  171  100
  215  457  304   11  393 1372 1949 1431  458  190  824  306  944  520
  211  732  398  459  488  547  792 1249  519  580  946  885  581 1035
  549  191  608  525  184  515 1704  169 1523 1796  214  428  914  579
  337  160 1438  117 3045  148 2009  545  292  404  367  791 1006  855
  124  916 2377  486 1186  853 2223  611 1187 1218 1156 1125  141 1379
  945 2133 1858  800  108  362 1650 1888 2588 1037  181  671  201 1737
  395  119 1916  619  526  423 1004  616  353 1371   26   16  118  455
 1220 2072  977  707 1521 1552  128 2374  524  738 1644  666  110  976
  758  271  637 1919  346  261  222 1768   89  612   66  251 1797  718
 1224   46 1012  322 1287 2193  618 1490 2039   67  943 1886 1126    6
 1312  950  584 1247  159 2040 1377 1980 1551 1978 2131  503  884  760
  788 2739 1947  161  426  240  617 1096 1736 1705  646 1977  352  506
  373   72  971 2650   77 1254 2008 2100  869 1316 1583 2164 1008 1069
 2681  947    9  281  810  698  372 2649  983 1918  242   19  490  429
  551  924  311 1065  820  650 1347  209   17   27   48 2772  291  915
   40 1043  900  210  394  912  312  383 2558  434  179   97  219  342
  376  529  942 2011  438  554  920  463  849 1157  677  859 1103 2163
 1642 1073  555 2313  647  880  527  676 2069 2070  828 1183  910 2252
 1835  301   36  262  851 1002  230  951 1104 2314  364  495 2315  493
  704  771   88  464  830  798 1289  130 1767  303   73  767  403  556
 1214 1285 1315  402  139 2161  759  468  585  607  636 2101 1001  475
  669  127   47 3015  474 2253 2770 1307 2345  673  212  273 1014  953
   80 2407  941  739 1408  973  889  991  858   78 2132  688 1950  708
  516 1589 1163  149  363 1185  315 1889  931  711 2833 2134 2680  769
  741  892   10 2711 1469  254 2222 2406  134  829  496  872 2742  280
 1034  954  789 1258  231  657   37  405 2528 2740 2285  170  780  668
  595 1407 2041 2466 2254  293  819  582 2224  505  535  220 1489 1195
  241  302 1948  101  790  638  473 1917  445  643 1611  770  727  109
  558  476  180 2346   56  407 1338  729 2343 1134  272 1053 2438 1077
 1776 1397 1153  615 1032  314  596  940 1715  333  413  323  282  606
 2435 1799 1522   98  484  648 1068 1402 1310 2282  223  221  442 1654
  313  162  565  566  199 1701  576  697   70 2436  981 2800 2130 3198
 1807  627 1244  285  414 1063 1011  557 1500  831  253  678  466 1246
  444 1433 1670 1093 1154 1184  494 1981  799  514 1711  454  586  680
  192  588  507  104 1094  626  832 2586  768 1550 2283 1346  992 1305
 2530 1196  415 1376 2376  392  922 2468  961  103 3229  544 3137  546
  465 1369 1591  172 2527  779 1275  263 1559  129  881  658 2589 1042
 1528 1855 2404  391  587 2073 2316 2165  260 2071 1622 1216 1410 1920
 1828 2619 1428 1380  504  485 2405 1337 1165  811  354 1762 2617 1734
  861 2803  483 1745 1164 1619  923  202  719 1033 1531 3260 2497  513
 1124  737 1560 1411 3107  890 1458  564  107 2012 1677 3168 1022  523
  902  748  232  891 2801  452  462 1530  728 1703 2344 1887 1640   71
 1442 2496 1499  193  787 1046  972 1045 1856 2709  778 1277 1348 2010
 1675 2831 1681  433  870  384  871 1520 1712  749  195  343 1306 1803
  879 2499 1833  591 1023 2864 1979  432  534 1366 3076  422 1084  841
  984  374  435 1561 1672 2373 1653 1155 2042 1859  645 1319 1562 1592
 1742  982  605  839  921 1367 1105  850 1581  453 1257  860 1136 2678
 1255 2375 1614 1288  985 1336 1318 2103  597 1245 1468 1620   41 2708
  131 1529 1501 1227  893 1197 2923  962 1256  736  656 1684 1194  750
  818 1015 1114  797  740  840  132 1166  687 1350  443  930 1470  499
  807 1609 1731  164 1519  862  284  952  497 2984 2221  560 1741  102
 1793 2954  679 1623  649  371 1317 1823  226  163 1680  809 1772  801
  537  133  635 2895 2647  385  446]
Columna 'SK_DPD_DEF':[   0    7   99    1  701    8    5   63   31 1158 1007   62  122   18
  610   12   30  189 1217   32  641  548  519   28 1401   79 3045 2377
 1035 2223  141   29 1187  458  213   60  367 2588 1919   46 1827  732
    6 1980 1707 1674  672   68  110 1219  822 1434   57 2164   93  761
  823  185   19   11  762  913   17 2772 1493    9 1584 1643 1918 1127
 2011 1250  456  944   27 2313 1339  821  169 2040  488  151   90 1249
 2374 2314  307 2315   61 1004  580  427  138 2161 3015   59  215 1278
  487  550  639 1037 1676  547  457   26 1218 1189  154  276  124  946
  975  977 2833 1311 1737  152   10  275  366 1159 2742 1036   16  304
  611 1248  731 1340 1096 1005 1797  245  336  130 1186 2102  123 2133
 1034 2224  305 1949   69   91 2284 2285 2041 2008   39  338 1462 1735
  824  397  383  943 2343 1523 2192 1615  854 1067  489  153  520 1279
 1704 1068   38 1552  609 2193  120 2252 2346 2800 3198  413  475  161
 1705 2466  702 1948 1402 1433 1583 1156  244  791 1981  640 2558 1796
 1582 2345  274 1950  792 2586 1097 1613 2530 1524  352  915 1799 2069
 2100 1280  853 3229 1766 1645 3137  976  852  883  184  214 1342  277
  183  428  444  671  182 2404 2073  260 2101  503  395  760 1920 1765
 2680 2282 2619 2162   48 1888 2405 1281 1431   49 2617  793  246 2376
 2803 1646  916 1125 1889  459  291 1309  335 3260  581  337  669  700
 1768 2527   89 1978 1400 3107  107 3168  763 1553 2131 1858 1554 2039
 2438 2496  885   92  243 1644 1856  322 2283  703  199  612  179  945
 2253  670  306 2222 2435  608  549   47 1069 1767 2499 1128 2864   80
  230 1066 2407  517 3076 2770  914 1006  172 2739 1736 2711  518 2406
 2497 1038 2071 2589 2678  973 2072  974 2254 1188 2650  426 1157  882
 1828 1370 2708  490 1403  579 2923 1492  578   42   56  216 1857  121
 2130 1065  884 2468 1372 2042  398 1917 1126  200 2010 1247 2984  396
   58 2221 2954 1887 2070 1371 2009 1432 2132 2895   77 1706 2647  855]

In [65]:
# Obtención de valores únicos para atributos categóricos.
for column in df.columns:
    # Evaluación si el tipo es string.
    if df[column].dtype == 'object':
        unique_values = df[column].unique()
        print(f"Columna '{column}': {unique_values}")

Columna 'NAME_CONTRACT_STATUS': ['Active' 'Completed' 'Demand' 'Signed' 'Sent proposal' 'Refused'
 'Approved']

### Mejoras de diseño

Dado que un sólo atributo es optimizable, se mantienen los datos en la tabla en el mismo estado en que se encuentran.

# installments_payments

### Analisis de datos preliminar

In [66]:
# Lectura del dataset.
csv_name = 'installments_payments.csv'
df = pd.read_csv(data_path + csv_name)

# Head del dataset.
df.info()

# Head del dataset.
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13605401 entries, 0 to 13605400
Data columns (total 8 columns):
 #   Column                  Dtype
---  ------                  -----
 0   SK_ID_PREV              int64
 1   SK_ID_CURR              int64
 2   NUM_INSTALMENT_VERSION  float64
 3   NUM_INSTALMENT_NUMBER   int64
 4   DAYS_INSTALMENT         float64
 5   DAYS_ENTRY_PAYMENT      float64
 6   AMT_INSTALMENT          float64
 7   AMT_PAYMENT             float64
dtypes: float64(5), int64(3)
memory usage: 830.4 MB

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.360,6948.360
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525,1716.525
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000,25425.000
3,2452527,199697,1.0,3,-2418.0,-2426.0,24350.130,24350.130
4,2714724,167756,1.0,2,-1383.0,-1366.0,2165.040,2160.585

In [67]:
# Obtención de valores únicos para atributos categóricos y numéricos no float.
for column in df.columns:
    unique_values = df[column].unique()

    # Indicador para verificar si la columna contiene algún valor float no entero (excluyendo NaN)
    contains_non_integer_float = False

    # Iterar sobre los valores únicos para encontrar floats no enteros
    for val in unique_values:
        # Verificar si el valor es un float y no es NaN
        if isinstance(val, float) and not np.isnan(val):
            # Verificar si el float tiene una parte decimal distinta de cero
            if val != int(val):
                contains_non_integer_float = True
                break  # Se encontró un float no entero, no es necesario seguir verificando

    # Si no se encontró ningún float no entero, imprimir los valores únicos de la columna
    if not contains_non_integer_float:
        print(f"Columna '{column}':{unique_values}")

Columna 'SK_ID_PREV':[1054186 1330831 2085231 ... 1984920 1946334 1276288]
Columna 'SK_ID_CURR':[161674 151639 193053 ... 413433 434445 405063]
Columna 'NUM_INSTALMENT_VERSION':[  1.   0.   2.   4.   3.   5.   7.   8.   6.  13.   9.  21.  22.  12.
  17.  18.  11.  14.  34.  33.  19.  16.  15.  10.  26.  27.  20.  25.
  23.  24.  31.  32.  28.  35.  29.  30.  43.  39.  40.  36.  41.  42.
  37.  38.  68.  44.  45.  46. 178.  52.  51.  53.  54.  49.  50.  58.
  57.  55.  56.  48.  47.  72.  59.  73.  61.]
Columna 'NUM_INSTALMENT_NUMBER':[  6  34   1   3   2  12  11   4  14   8  20  56   7  23  38 116   5  46
 106   9 105  88  30  16  65  19  15  57  10  41  84  49  59 107  17  94
  64  28  24 140  43  99  69  13  22  85  29  83  73 139  39  18  26  25
  21  44  27  31  37  63  45  78  53  92 112  36  93 114  58  32  67  47
  68  40  81  61 117  60  75 149  35  48  82  79  71  51  72  80 156  42
  50 148  33  55 103  54 180  86 113  87  62 102 115 142 164 162 101  91
  96 100 104 121  66 123  52  89  70 124  76  97 134 165 135  77 128 125
 118 122 153  95 109 158 132 120 111 151 133 119 129  98 173 127  90 168
 138  74 150 108 145 147 152 130 146 154 196 210 110 144 136 170 190 126
 191 171 131 178 155 157 181 183 169 137 207 143 163 159 195 200 177 176
 187 184 198 167 141 175 160 161 188 185 186 182 174 194 179 197 216 172
 189 208 237 166 203 217 205 202 199 204 231 192 220 201 211 193 209 227
 206 221 213 219 244 214 229 233 224 218 226 222 230 215 212 228 223 225
 240 235 234 239 232 236 238 242 241 252 273 271 275 254 269 256 251 247
 248 266 262 263 265 253 245 250 268 260 243 264 261 255 246 267 249 259
 257 272 258 270 277 274 276]
Columna 'DAYS_INSTALMENT':[-1.180e+03 -2.156e+03 -6.300e+01 ... -2.921e+03 -2.551e+03 -1.000e+00]
Columna 'DAYS_ENTRY_PAYMENT':[-1187. -2156.   -63. ... -3023. -3061. -3096.]

In [68]:
# Obtención de valores únicos para atributos categóricos.
for column in df.columns:
    # Evaluación si el tipo es string.
    if df[column].dtype == 'object':
        unique_values = df[column].unique()
        print(f"Columna '{column}': {unique_values}")

### Mejoras de diseño

Dado que un sólo atributo es optimizable, se mantienen los datos en la tabla en el mismo estado en que se encuentran.

### Exportación de DataFrames a CSV

Este paso guarda el DataFrame principal y cada una de las tablas de dimensiones creadas en archivos CSV individuales. Esto permite un almacenamiento y uso posterior más sencillo de los datos normalizados y las tablas de referencia.

In [ ]:
# Creacion de directorio output.
ref_name = csv_name.replace('.csv', '')
extract_dir = output_dir + ref_name + '/'

# Evaluacion de existencia del directorio.
if not os.path.exists(extract_dir):
    os.makedirs(extract_dir)

# Guardar el dataFrame principal 'df' en un archivo CSV.
df.to_csv(extract_dir + csv_name, index=False)
print(f'DataFrame principal guardado como {csv_name}')

# Guardar cada tabla de dimensiones en un archivo CSV separado
for name, dim_df in dimension_tables.items():
    file_name = f'{name}.csv'
    dim_df.to_csv(extract_dir + file_name, index=False)
    print(f'Tabla de dimensiones "{name}" guardada como {file_name}')

# POS_CASH_balance

### Analisis de datos preliminar

In [69]:
# Lectura del dataset.
csv_name = 'POS_CASH_balance.csv'
df = pd.read_csv(data_path + csv_name)

# Head del dataset.
df.info()

# Head del dataset.
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001358 entries, 0 to 10001357
Data columns (total 8 columns):
 #   Column                 Dtype
---  ------                 -----
 0   SK_ID_PREV             int64
 1   SK_ID_CURR             int64
 2   MONTHS_BALANCE         int64
 3   CNT_INSTALMENT         float64
 4   CNT_INSTALMENT_FUTURE  float64
 5   NAME_CONTRACT_STATUS   object
 6   SK_DPD                 int64
 7   SK_DPD_DEF             int64
dtypes: float64(2), int64(5), object(1)
memory usage: 610.4+ MB

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0

In [70]:
# Obtención de valores únicos para atributos categóricos y numéricos no float.
for column in df.columns:
    unique_values = df[column].unique()

    # Indicador para verificar si la columna contiene algún valor float no entero (excluyendo NaN)
    contains_non_integer_float = False

    # Iterar sobre los valores únicos para encontrar floats no enteros
    for val in unique_values:
        # Verificar si el valor es un float y no es NaN
        if isinstance(val, float) and not np.isnan(val):
            # Verificar si el float tiene una parte decimal distinta de cero
            if val != int(val):
                contains_non_integer_float = True
                break  # Se encontró un float no entero, no es necesario seguir verificando

    # Si no se encontró ningún float no entero, imprimir los valores únicos de la columna
    if not contains_non_integer_float:
        print(f"Columna '{column}':{unique_values}")

Columna 'SK_ID_PREV':[1803195 1715348 1784872 ... 2452932 1980876 2308284]
Columna 'SK_ID_CURR':[182943 367990 397406 ... 394310 240059 144536]
Columna 'MONTHS_BALANCE':[-31 -33 -32 -35 -38 -39 -34 -41 -37 -40 -43 -36 -42 -47 -44 -46 -45 -27
 -25 -24 -30 -28 -26 -29 -48 -15 -19 -22 -14 -18 -16 -21 -17 -20 -23  -1
  -6  -2  -3  -5  -4 -13 -11 -10  -9  -7  -8 -54 -49 -52 -53 -50 -51 -55
 -12 -94 -95 -92 -91 -96 -93 -57 -64 -56 -59 -60 -66 -65 -58 -63 -62 -61
 -87 -86 -88 -89 -90 -72 -74 -73 -82 -78 -81 -75 -77 -80 -76 -79 -69 -70
 -71 -68 -67 -83 -85 -84]
Columna 'CNT_INSTALMENT':[48. 36. 12. 24. 60. 18.  4. 42. 25. 14. 16. 13.  8. 10. 15. 11. 30. 54.
  6.  9.  5. 17.  3.  2. 20. 32. nan  1.  7. 47. 49. 28. 43. 23. 21. 19.
 39. 37. 35. 27. 22. 41. 31. 61. 26. 34. 29. 44. 55. 33. 66. 46. 59. 38.
 72. 40. 57. 45. 92. 56. 84. 51. 52. 58. 62. 53. 64. 50. 77. 70. 81. 63.
 71. 68.]
Columna 'CNT_INSTALMENT_FUTURE':[45. 35.  9. 42. 12. 43. 36. 16. 24.  5. 15.  1. 28. 23. 56. 11.  7. 18.
 17. 46. 21.  0.  4. 40. 32. 19.  8. 10.  2. 13. 14.  3.  6. 48. 22. 34.
 47. 30. 29. 41. 54. 20. 37. 31. 27. 26. nan 25. 38. 33. 39. 53. 58. 50.
 51. 52. 55. 59. 57. 60. 49. 44. 61. 68. 66. 70. 69. 64. 62. 63. 67. 85.
 65. 80. 72. 82. 71. 83. 81. 84.]
Columna 'NAME_CONTRACT_STATUS':['Active' 'Completed' 'Signed' 'Approved' 'Returned to the store' 'Demand'
 'Canceled' 'XNA' 'Amortized debt']
Columna 'SK_DPD':[   0    1    2 ... 3989 3716 3082]
Columna 'SK_DPD_DEF':[   0    1    2 ... 2806 2376 2495]

In [71]:
# Obtención de valores únicos para atributos categóricos.
for column in df.columns:
    # Evaluación si el tipo es string.
    if df[column].dtype == 'object':
        unique_values = df[column].unique()
        print(f"Columna '{column}': {unique_values}")

Columna 'NAME_CONTRACT_STATUS': ['Active' 'Completed' 'Signed' 'Approved' 'Returned to the store' 'Demand'
 'Canceled' 'XNA' 'Amortized debt']

### Mejoras de diseño

Dado que un sólo atributo es optimizable, se mantienen los datos en la tabla en el mismo estado en que se encuentran.

### Exportación de DataFrames a CSV

Este paso guarda el DataFrame principal y cada una de las tablas de dimensiones creadas en archivos CSV individuales. Esto permite un almacenamiento y uso posterior más sencillo de los datos normalizados y las tablas de referencia.

In [ ]:
# Creacion de directorio output.
ref_name = csv_name.replace('.csv', '')
extract_dir = output_dir + ref_name + '/'

# Evaluacion de existencia del directorio.
if not os.path.exists(extract_dir):
    os.makedirs(extract_dir)

# Guardar el dataFrame principal 'df' en un archivo CSV.
df.to_csv(extract_dir + csv_name, index=False)
print(f'DataFrame principal guardado como {csv_name}')

# Guardar cada tabla de dimensiones en un archivo CSV separado
for name, dim_df in dimension_tables.items():
    file_name = f'{name}.csv'
    dim_df.to_csv(extract_dir + file_name, index=False)
    print(f'Tabla de dimensiones "{name}" guardada como {file_name}')

# previous_application

### Analisis de datos preliminar

In [72]:
# Lectura del dataset.
csv_name = 'previous_application.csv'
df = pd.read_csv(data_path + csv_name)

# Head del dataset.
df.info()

# Head del dataset.
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1670214 entries, 0 to 1670213
Data columns (total 37 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   SK_ID_PREV                   1670214 non-null  int64
 1   SK_ID_CURR                   1670214 non-null  int64
 2   NAME_CONTRACT_TYPE           1670214 non-null  object
 3   AMT_ANNUITY                  1297979 non-null  float64
 4   AMT_APPLICATION              1670214 non-null  float64
 5   AMT_CREDIT                   1670213 non-null  float64
 6   AMT_DOWN_PAYMENT             774370 non-null   float64
 7   AMT_GOODS_PRICE              1284699 non-null  float64
 8   WEEKDAY_APPR_PROCESS_START   1670214 non-null  object
 9   HOUR_APPR_PROCESS_START      1670214 non-null  int64
 10  FLAG_LAST_APPL_PER_CONTRACT  1670214 non-null  object
 11  NFLAG_LAST_APPL_IN_DAY       1670214 non-null  int64
 12  RATE_DOWN_PAYMENT            774370 non-null   float64
 13  RATE_INTEREST_PRIMARY        5951 non-null     float64
 14  RATE_INTEREST_PRIVILEGED     5951 non-null     float64
 15  NAME_CASH_LOAN_PURPOSE       1670214 non-null  object
 16  NAME_CONTRACT_STATUS         1670214 non-null  object
 17  DAYS_DECISION                1670214 non-null  int64
 18  NAME_PAYMENT_TYPE            1670214 non-null  object
 19  CODE_REJECT_REASON           1670214 non-null  object
 20  NAME_TYPE_SUITE              849809 non-null   object
 21  NAME_CLIENT_TYPE             1670214 non-null  object
 22  NAME_GOODS_CATEGORY          1670214 non-null  object
 23  NAME_PORTFOLIO               1670214 non-null  object
 24  NAME_PRODUCT_TYPE            1670214 non-null  object
 25  CHANNEL_TYPE                 1670214 non-null  object
 26  SELLERPLACE_AREA             1670214 non-null  int64
 27  NAME_SELLER_INDUSTRY         1670214 non-null  object
 28  CNT_PAYMENT                  1297984 non-null  float64
 29  NAME_YIELD_GROUP             1670214 non-null  object
 30  PRODUCT_COMBINATION          1669868 non-null  object
 31  DAYS_FIRST_DRAWING           997149 non-null   float64
 32  DAYS_FIRST_DUE               997149 non-null   float64
 33  DAYS_LAST_DUE_1ST_VERSION    997149 non-null   float64
 34  DAYS_LAST_DUE                997149 non-null   float64
 35  DAYS_TERMINATION             997149 non-null   float64
 36  NFLAG_INSURED_ON_APPROVAL    997149 non-null   float64
dtypes: float64(15), int64(6), object(16)
memory usage: 471.5+ MB

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
# Obtención de valores únicos para atributos categóricos y numéricos no float.
for column in df.columns:
    unique_values = df[column].unique()

    # Indicador para verificar si la columna contiene algún valor float no entero (excluyendo NaN)
    contains_non_integer_float = False

    # Iterar sobre los valores únicos para encontrar floats no enteros
    for val in unique_values:
        # Verificar si el valor es un float y no es NaN
        if isinstance(val, float) and not np.isnan(val):
            # Verificar si el float tiene una parte decimal distinta de cero
            if val != int(val):
                contains_non_integer_float = True
                break  # Se encontró un float no entero, no es necesario seguir verificando

    # Si no se encontró ningún float no entero, imprimir los valores únicos de la columna
    if not contains_non_integer_float:
        print(f"Columna '{column}':{unique_values}")

Columna 'SK_ID_PREV':[2030495 2802425 2523466 ... 2659632 2785582 2418762]
Columna 'SK_ID_CURR':[271877 108129 122040 ... 253940 353284 191629]
Columna 'NAME_CONTRACT_TYPE':['Consumer loans' 'Cash loans' 'Revolving loans' 'XNA']
Columna 'WEEKDAY_APPR_PROCESS_START':['SATURDAY' 'THURSDAY' 'TUESDAY' 'MONDAY' 'FRIDAY' 'SUNDAY' 'WEDNESDAY']
Columna 'HOUR_APPR_PROCESS_START':[15 11  7  9  8 10 12 13 14 16  6  4  5 19 17 18 20 22 21  3  1  2 23  0]
Columna 'FLAG_LAST_APPL_PER_CONTRACT':['Y' 'N']
Columna 'NFLAG_LAST_APPL_IN_DAY':[1 0]
Columna 'NAME_CASH_LOAN_PURPOSE':['XAP' 'XNA' 'Repairs' 'Everyday expenses' 'Car repairs'
 'Building a house or an annex' 'Other' 'Journey'
 'Purchase of electronic equipment' 'Medicine' 'Payments on other loans'
 'Urgent needs' 'Buying a used car' 'Buying a new car'
 'Buying a holiday home / land' 'Education' 'Buying a home' 'Furniture'
 'Buying a garage' 'Business development' 'Wedding / gift / holiday'
 'Hobby' 'Gasification / water supply' 'Refusal to name the goal'
 'Money for a third person']
Columna 'NAME_CONTRACT_STATUS':['Approved' 'Refused' 'Canceled' 'Unused offer']
Columna 'DAYS_DECISION':[  -73  -164  -301 ... -1967 -2389    -1]
Columna 'NAME_PAYMENT_TYPE':['Cash through the bank' 'XNA' 'Non-cash from your account'
 'Cashless from the account of the employer']
Columna 'CODE_REJECT_REASON':['XAP' 'HC' 'LIMIT' 'CLIENT' 'SCOFR' 'SCO' 'XNA' 'VERIF' 'SYSTEM']
Columna 'NAME_TYPE_SUITE':[nan 'Unaccompanied' 'Spouse, partner' 'Family' 'Children' 'Other_B'
 'Other_A' 'Group of people']
Columna 'NAME_CLIENT_TYPE':['Repeater' 'New' 'Refreshed' 'XNA']
Columna 'NAME_GOODS_CATEGORY':['Mobile' 'XNA' 'Consumer Electronics' 'Construction Materials'
 'Auto Accessories' 'Photo / Cinema Equipment' 'Computers' 'Audio/Video'
 'Medicine' 'Clothing and Accessories' 'Furniture' 'Sport and Leisure'
 'Homewares' 'Gardening' 'Jewelry' 'Vehicles' 'Education'
 'Medical Supplies' 'Other' 'Direct Sales' 'Office Appliances' 'Fitness'
 'Tourism' 'Insurance' 'Additional Service' 'Weapon' 'Animals'
 'House Construction']
Columna 'NAME_PORTFOLIO':['POS' 'Cash' 'XNA' 'Cards' 'Cars']
Columna 'NAME_PRODUCT_TYPE':['XNA' 'x-sell' 'walk-in']
Columna 'CHANNEL_TYPE':['Country-wide' 'Contact center' 'Credit and cash offices' 'Stone'
 'Regional / Local' 'AP+ (Cash loan)' 'Channel of corporate sales'
 'Car dealer']
Columna 'SELLERPLACE_AREA':[  35   -1  200 ... 2233  887 2420]
Columna 'NAME_SELLER_INDUSTRY':['Connectivity' 'XNA' 'Consumer electronics' 'Industry' 'Clothing'
 'Furniture' 'Construction' 'Jewelry' 'Auto technology' 'MLM partners'
 'Tourism']
Columna 'CNT_PAYMENT':[12. 36. 24. 18. nan 54. 30.  8.  3.  6.  0. 48. 10. 60. 42.  4.  5. 16.
 20.  7. 14.  9. 22. 15. 11. 13. 17. 26. 23. 38. 33. 72. 59. 34. 84. 28.
 41. 66. 29. 32. 44. 39. 40. 46. 35. 19. 47. 45. 21. 53.]
Columna 'NAME_YIELD_GROUP':['middle' 'low_action' 'high' 'low_normal' 'XNA']
Columna 'PRODUCT_COMBINATION':['POS mobile with interest' 'Cash X-Sell: low' 'Cash X-Sell: high'
 'Cash X-Sell: middle' 'Cash Street: high' 'Cash'
 'POS household without interest' 'POS household with interest'
 'POS other with interest' 'Card X-Sell' 'POS mobile without interest'
 'Card Street' 'POS industry with interest' 'Cash Street: low'
 'POS industry without interest' 'Cash Street: middle'
 'POS others without interest' nan]
Columna 'DAYS_FIRST_DRAWING':[ 3.65243e+05          nan -2.77000e+02 ... -1.61100e+03 -1.77000e+03
 -1.87900e+03]
Columna 'DAYS_FIRST_DUE':[  -42.  -134.  -271. ... -2842. -1774. -2892.]
Columna 'DAYS_LAST_DUE_1ST_VERSION':[ 300.  916.   59. ... 1878. 2016. 1760.]
Columna 'DAYS_LAST_DUE':[-4.20000e+01  3.65243e+05 -1.82000e+02 ... -2.86700e+03 -2.86600e+03
 -2.83300e+03]
Columna 'DAYS_TERMINATION':[-3.70000e+01  3.65243e+05 -1.77000e+02 ... -2.82800e+03 -2.87000e+03
 -2.81500e+03]
Columna 'NFLAG_INSURED_ON_APPROVAL':[ 0.  1. nan]

In [74]:
# Obtención de valores únicos para atributos categóricos.
for column in df.columns:
    # Evaluación si el tipo es string.
    if df[column].dtype == 'object':
        unique_values = df[column].unique()
        print(f"Columna '{column}': {unique_values}")

Columna 'NAME_CONTRACT_TYPE': ['Consumer loans' 'Cash loans' 'Revolving loans' 'XNA']
Columna 'WEEKDAY_APPR_PROCESS_START': ['SATURDAY' 'THURSDAY' 'TUESDAY' 'MONDAY' 'FRIDAY' 'SUNDAY' 'WEDNESDAY']
Columna 'FLAG_LAST_APPL_PER_CONTRACT': ['Y' 'N']
Columna 'NAME_CASH_LOAN_PURPOSE': ['XAP' 'XNA' 'Repairs' 'Everyday expenses' 'Car repairs'
 'Building a house or an annex' 'Other' 'Journey'
 'Purchase of electronic equipment' 'Medicine' 'Payments on other loans'
 'Urgent needs' 'Buying a used car' 'Buying a new car'
 'Buying a holiday home / land' 'Education' 'Buying a home' 'Furniture'
 'Buying a garage' 'Business development' 'Wedding / gift / holiday'
 'Hobby' 'Gasification / water supply' 'Refusal to name the goal'
 'Money for a third person']
Columna 'NAME_CONTRACT_STATUS': ['Approved' 'Refused' 'Canceled' 'Unused offer']
Columna 'NAME_PAYMENT_TYPE': ['Cash through the bank' 'XNA' 'Non-cash from your account'
 'Cashless from the account of the employer']
Columna 'CODE_REJECT_REASON': ['XAP' 'HC' 'LIMIT' 'CLIENT' 'SCOFR' 'SCO' 'XNA' 'VERIF' 'SYSTEM']
Columna 'NAME_TYPE_SUITE': [nan 'Unaccompanied' 'Spouse, partner' 'Family' 'Children' 'Other_B'
 'Other_A' 'Group of people']
Columna 'NAME_CLIENT_TYPE': ['Repeater' 'New' 'Refreshed' 'XNA']
Columna 'NAME_GOODS_CATEGORY': ['Mobile' 'XNA' 'Consumer Electronics' 'Construction Materials'
 'Auto Accessories' 'Photo / Cinema Equipment' 'Computers' 'Audio/Video'
 'Medicine' 'Clothing and Accessories' 'Furniture' 'Sport and Leisure'
 'Homewares' 'Gardening' 'Jewelry' 'Vehicles' 'Education'
 'Medical Supplies' 'Other' 'Direct Sales' 'Office Appliances' 'Fitness'
 'Tourism' 'Insurance' 'Additional Service' 'Weapon' 'Animals'
 'House Construction']
Columna 'NAME_PORTFOLIO': ['POS' 'Cash' 'XNA' 'Cards' 'Cars']
Columna 'NAME_PRODUCT_TYPE': ['XNA' 'x-sell' 'walk-in']
Columna 'CHANNEL_TYPE': ['Country-wide' 'Contact center' 'Credit and cash offices' 'Stone'
 'Regional / Local' 'AP+ (Cash loan)' 'Channel of corporate sales'
 'Car dealer']
Columna 'NAME_SELLER_INDUSTRY': ['Connectivity' 'XNA' 'Consumer electronics' 'Industry' 'Clothing'
 'Furniture' 'Construction' 'Jewelry' 'Auto technology' 'MLM partners'
 'Tourism']
Columna 'NAME_YIELD_GROUP': ['middle' 'low_action' 'high' 'low_normal' 'XNA']
Columna 'PRODUCT_COMBINATION': ['POS mobile with interest' 'Cash X-Sell: low' 'Cash X-Sell: high'
 'Cash X-Sell: middle' 'Cash Street: high' 'Cash'
 'POS household without interest' 'POS household with interest'
 'POS other with interest' 'Card X-Sell' 'POS mobile without interest'
 'Card Street' 'POS industry with interest' 'Cash Street: low'
 'POS industry without interest' 'Cash Street: middle'
 'POS others without interest' nan]

### Mejoras de diseño

In [75]:
# Creación de copia para control posterior.
df_backup = df.copy()

In [76]:
# Obtención de atributos categoricos.
dimension_tables = {}
categorical_columns = [col for col in df.columns if df[col].dtype == 'object']

In [77]:
# Creación de tablas de dimensiones.
for col in categorical_columns:
    # Extraer valores únicos no NaN para la tabla de dimensión
    unique_values = df[col].dropna().unique()

    if len(unique_values) > 0:
        # Crear una tabla de dimensión para la columna categórica actual
        dim_df = pd.DataFrame({
            f'{col}_ID': range(1, len(unique_values) + 1),
            col: unique_values
        })
        dimension_tables[f'dim_{col.lower()}'] = dim_df

        # Crear un mapeo desde el valor original al nuevo ID, manejando NaN
        mapping = dict(zip(dim_df[col], dim_df[f'{col}_ID']))

        # Reemplazar los valores categóricos en el DataFrame original con sus IDs
        # Usar .map() que maneja valores NaN por defecto, preservándolos si no están en el mapeo
        df[col] = df[col].map(mapping)

        # Renombrar la columna para reflejar que ahora contiene IDs
        df.rename(columns={col: f'{col}_ID'}, inplace=True)
    else:
        print(f"La columna '{col}' no tiene valores únicos que no estén vacios, por lo tanto se omite la creación de la tabla de dimensión.")

In [78]:
# Control de atributos.
print(f'Recuento de columnas categoricas: {len(categorical_columns)}')
print(f'Recuento de tablas de dimensiones: {len(dimension_tables)}')

Recuento de columnas categoricas: 16
Recuento de tablas de dimensiones: 16

In [79]:
# Tablas de dimensiones.
print(f'Tablas de dimensiones: {[*dimension_tables.keys()]}')

Tablas de dimensiones: ['dim_name_contract_type', 'dim_weekday_appr_process_start', 'dim_flag_last_appl_per_contract', 'dim_name_cash_loan_purpose', 'dim_name_contract_status', 'dim_name_payment_type', 'dim_code_reject_reason', 'dim_name_type_suite', 'dim_name_client_type', 'dim_name_goods_category', 'dim_name_portfolio', 'dim_name_product_type', 'dim_channel_type', 'dim_name_seller_industry', 'dim_name_yield_group', 'dim_product_combination']

In [80]:
# Print de atributos del dataset backup.
print(f'Columnas del dataset de referencia: {[*df_backup.columns]}')

Columnas del dataset de referencia: ['SK_ID_PREV', 'SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY', 'AMT_APPLICATION', 'AMT_CREDIT', 'AMT_DOWN_PAYMENT', 'AMT_GOODS_PRICE', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'FLAG_LAST_APPL_PER_CONTRACT', 'NFLAG_LAST_APPL_IN_DAY', 'RATE_DOWN_PAYMENT', 'RATE_INTEREST_PRIMARY', 'RATE_INTEREST_PRIVILEGED', 'NAME_CASH_LOAN_PURPOSE', 'NAME_CONTRACT_STATUS', 'DAYS_DECISION', 'NAME_PAYMENT_TYPE', 'CODE_REJECT_REASON', 'NAME_TYPE_SUITE', 'NAME_CLIENT_TYPE', 'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE', 'CHANNEL_TYPE', 'SELLERPLACE_AREA', 'NAME_SELLER_INDUSTRY', 'CNT_PAYMENT', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION', 'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION', 'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL']

In [81]:
# Query para la verificación del join de tablas principal y de dimensiones.
query = f"""
SELECT {', '.join(df_backup.columns)}
FROM df
"""

dim_tables_names = [*dimension_tables.keys()]

for dim_table_name in dim_tables_names:
  dim_table_id = dimension_tables[dim_table_name].columns[0]

  query += f"""
  LEFT JOIN {dim_table_name} ON df.{dim_table_id} = {dim_table_name}.{dim_table_id}
  """

In [82]:
# Impresion de la query.
print(query)

SELECT SK_ID_PREV, SK_ID_CURR, NAME_CONTRACT_TYPE, AMT_ANNUITY, AMT_APPLICATION, AMT_CREDIT, AMT_DOWN_PAYMENT, AMT_GOODS_PRICE, WEEKDAY_APPR_PROCESS_START, HOUR_APPR_PROCESS_START, FLAG_LAST_APPL_PER_CONTRACT, NFLAG_LAST_APPL_IN_DAY, RATE_DOWN_PAYMENT, RATE_INTEREST_PRIMARY, RATE_INTEREST_PRIVILEGED, NAME_CASH_LOAN_PURPOSE, NAME_CONTRACT_STATUS, DAYS_DECISION, NAME_PAYMENT_TYPE, CODE_REJECT_REASON, NAME_TYPE_SUITE, NAME_CLIENT_TYPE, NAME_GOODS_CATEGORY, NAME_PORTFOLIO, NAME_PRODUCT_TYPE, CHANNEL_TYPE, SELLERPLACE_AREA, NAME_SELLER_INDUSTRY, CNT_PAYMENT, NAME_YIELD_GROUP, PRODUCT_COMBINATION, DAYS_FIRST_DRAWING, DAYS_FIRST_DUE, DAYS_LAST_DUE_1ST_VERSION, DAYS_LAST_DUE, DAYS_TERMINATION, NFLAG_INSURED_ON_APPROVAL
FROM df

  LEFT JOIN dim_name_contract_type ON df.NAME_CONTRACT_TYPE_ID = dim_name_contract_type.NAME_CONTRACT_TYPE_ID

  LEFT JOIN dim_weekday_appr_process_start ON df.WEEKDAY_APPR_PROCESS_START_ID = dim_weekday_appr_process_start.WEEKDAY_APPR_PROCESS_START_ID

  LEFT JOIN dim_flag_last_appl_per_contract ON df.FLAG_LAST_APPL_PER_CONTRACT_ID = dim_flag_last_appl_per_contract.FLAG_LAST_APPL_PER_CONTRACT_ID

  LEFT JOIN dim_name_cash_loan_purpose ON df.NAME_CASH_LOAN_PURPOSE_ID = dim_name_cash_loan_purpose.NAME_CASH_LOAN_PURPOSE_ID

  LEFT JOIN dim_name_contract_status ON df.NAME_CONTRACT_STATUS_ID = dim_name_contract_status.NAME_CONTRACT_STATUS_ID

  LEFT JOIN dim_name_payment_type ON df.NAME_PAYMENT_TYPE_ID = dim_name_payment_type.NAME_PAYMENT_TYPE_ID

  LEFT JOIN dim_code_reject_reason ON df.CODE_REJECT_REASON_ID = dim_code_reject_reason.CODE_REJECT_REASON_ID

  LEFT JOIN dim_name_type_suite ON df.NAME_TYPE_SUITE_ID = dim_name_type_suite.NAME_TYPE_SUITE_ID

  LEFT JOIN dim_name_client_type ON df.NAME_CLIENT_TYPE_ID = dim_name_client_type.NAME_CLIENT_TYPE_ID

  LEFT JOIN dim_name_goods_category ON df.NAME_GOODS_CATEGORY_ID = dim_name_goods_category.NAME_GOODS_CATEGORY_ID

  LEFT JOIN dim_name_portfolio ON df.NAME_PORTFOLIO_ID = dim_name_portfolio.NAME_PORTFOLIO_ID

  LEFT JOIN dim_name_product_type ON df.NAME_PRODUCT_TYPE_ID = dim_name_product_type.NAME_PRODUCT_TYPE_ID

  LEFT JOIN dim_channel_type ON df.CHANNEL_TYPE_ID = dim_channel_type.CHANNEL_TYPE_ID

  LEFT JOIN dim_name_seller_industry ON df.NAME_SELLER_INDUSTRY_ID = dim_name_seller_industry.NAME_SELLER_INDUSTRY_ID

  LEFT JOIN dim_name_yield_group ON df.NAME_YIELD_GROUP_ID = dim_name_yield_group.NAME_YIELD_GROUP_ID

  LEFT JOIN dim_product_combination ON df.PRODUCT_COMBINATION_ID = dim_product_combination.PRODUCT_COMBINATION_ID

In [83]:
# Control de join de tablas descompuestas.

# Construcción de diccionario con dataframe principal y dataframes de dimensiones.
env = {**dimension_tables, 'df': df}

# Ejecución de la query.
control_df = sqldf(query, env) # sqldf(query, locals())
control_df.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
# Shape de control_df.
control_df.shape

(1670214, 37)

In [85]:
# Reemplazo de NoneType por np.nans.
for col in control_df.columns:
    # Verificacion si 'None' (NoneType) está presente en la columna.
    if control_df[col].apply(lambda x: x is None).any():
        control_df[col] = control_df[col].replace({None: np.nan})

print("Valores None fueron reemplazados con np.nan para todas las columnas de control_df.")

Valores None fueron reemplazados con np.nan para todas las columnas de control_df.

In [86]:
# Cotejo final de control_df con df_backup.

matching_counts = {}

# Asegurar que solo comparamos las columnas que existen en ambos DataFrames.
columns_to_compare = [col for col in df_backup.columns if col in control_df.columns]

for col in columns_to_compare:
    s1 = control_df[col]
    s2 = df_backup[col]

    # Comparar valores, tratando np.nan como iguales si ambos lo son
    # Esto gestiona tanto valores iguales no nulos (s1 == s2) como coincidencias NaN-NaN (s1.isna() & s2.isna())
    matches = ((s1 == s2) | (s1.isna() & s2.isna()))
    matching_counts[col] = matches.sum()

# Crear un DataFrame para visualizar mejor los resultados
comparison_df = pd.DataFrame(matching_counts.items(), columns=['Column', 'Matching_Count'])
comparison_df['Total_Rows'] = len(df_backup)
comparison_df['Percentage_Match'] = (comparison_df['Matching_Count'] / comparison_df['Total_Rows']) * 100

display(comparison_df)

# Opcionalmente, mostrar columnas que no tienen un 100% de coincidencia para facilitar la inspección
non_full_match_cols = comparison_df[comparison_df['Percentage_Match'] < 100]
if not non_full_match_cols.empty:
    print("\nColumnas con menos del 100% de coincidencia (debido a diferencias reales de valores, no solo manejo de NaN):")
    display(non_full_match_cols)
else:
    print("\nTodas las columnas comparadas tienen una coincidencia del 100% (incluyendo la igualdad NaN-NaN).")

                         Column  Matching_Count  Total_Rows  Percentage_Match
0                    SK_ID_PREV         1670214     1670214             100.0
1                    SK_ID_CURR         1670214     1670214             100.0
2            NAME_CONTRACT_TYPE         1670214     1670214             100.0
3                   AMT_ANNUITY         1670214     1670214             100.0
4               AMT_APPLICATION         1670214     1670214             100.0
5                    AMT_CREDIT         1670214     1670214             100.0
6              AMT_DOWN_PAYMENT         1670214     1670214             100.0
7               AMT_GOODS_PRICE         1670214     1670214             100.0
8    WEEKDAY_APPR_PROCESS_START         1670214     1670214             100.0
9       HOUR_APPR_PROCESS_START         1670214     1670214             100.0
10  FLAG_LAST_APPL_PER_CONTRACT         1670214     1670214             100.0
11       NFLAG_LAST_APPL_IN_DAY         1670214     1670214             100.0
12            RATE_DOWN_PAYMENT         1670214     1670214             100.0
13        RATE_INTEREST_PRIMARY         1670214     1670214             100.0
14     RATE_INTEREST_PRIVILEGED         1670214     1670214             100.0
15       NAME_CASH_LOAN_PURPOSE         1670214     1670214             100.0
16         NAME_CONTRACT_STATUS         1670214     1670214             100.0
17                DAYS_DECISION         1670214     1670214             100.0
18            NAME_PAYMENT_TYPE         1670214     1670214             100.0
19           CODE_REJECT_REASON         1670214     1670214             100.0
20              NAME_TYPE_SUITE         1670214     1670214             100.0
21             NAME_CLIENT_TYPE         1670214     1670214             100.0
22          NAME_GOODS_CATEGORY         1670214     1670214             100.0
23               NAME_PORTFOLIO         1670214     1670214             100.0
24            NAME_PRODUCT_TYPE         1670214     1670214             100.0
25                 CHANNEL_TYPE         1670214     1670214             100.0
26             SELLERPLACE_AREA         1670214     1670214             100.0
27         NAME_SELLER_INDUSTRY         1670214     1670214             100.0
28                  CNT_PAYMENT         1670214     1670214             100.0
29             NAME_YIELD_GROUP         1670214     1670214             100.0
30          PRODUCT_COMBINATION         1670214     1670214             100.0
31           DAYS_FIRST_DRAWING         1670214     1670214             100.0
32               DAYS_FIRST_DUE         1670214     1670214             100.0
33    DAYS_LAST_DUE_1ST_VERSION         1670214     1670214             100.0
34                DAYS_LAST_DUE         1670214     1670214             100.0
35             DAYS_TERMINATION         1670214     1670214             100.0
36    NFLAG_INSURED_ON_APPROVAL         1670214     1670214             100.0

Todas las columnas comparadas tienen una coincidencia del 100% (incluyendo la igualdad NaN-NaN).

### Exportación de DataFrames a CSV

Este paso guarda el DataFrame principal y cada una de las tablas de dimensiones creadas en archivos CSV individuales. Esto permite un almacenamiento y uso posterior más sencillo de los datos normalizados y las tablas de referencia.

In [87]:
# Creacion de directorio output.
ref_name = csv_name.replace('.csv', '')
extract_dir = output_dir + ref_name + '/'

# Evaluacion de existencia del directorio.
if not os.path.exists(extract_dir):
    os.makedirs(extract_dir)

# Guardar el dataFrame principal 'df' en un archivo CSV.
df.to_csv(extract_dir + csv_name, index=False)
print(f'DataFrame principal guardado como {csv_name}')

# Guardar cada tabla de dimensiones en un archivo CSV separado
for name, dim_df in dimension_tables.items():
    file_name = f'{name}.csv'
    dim_df.to_csv(extract_dir + file_name, index=False)
    print(f'Tabla de dimensiones "{name}" guardada como {file_name}')

DataFrame principal guardado como previous_application.csv
Tabla de dimensiones "dim_name_contract_type" guardada como dim_name_contract_type.csv
Tabla de dimensiones "dim_weekday_appr_process_start" guardada como dim_weekday_appr_process_start.csv
Tabla de dimensiones "dim_flag_last_appl_per_contract" guardada como dim_flag_last_appl_per_contract.csv
Tabla de dimensiones "dim_name_cash_loan_purpose" guardada como dim_name_cash_loan_purpose.csv
Tabla de dimensiones "dim_name_contract_status" guardada como dim_name_contract_status.csv
Tabla de dimensiones "dim_name_payment_type" guardada como dim_name_payment_type.csv
Tabla de dimensiones "dim_code_reject_reason" guardada como dim_code_reject_reason.csv
Tabla de dimensiones "dim_name_type_suite" guardada como dim_name_type_suite.csv
Tabla de dimensiones "dim_name_client_type" guardada como dim_name_client_type.csv
Tabla de dimensiones "dim_name_goods_category" guardada como dim_name_goods_category.csv
Tabla de dimensiones "dim_name_portfolio" guardada como dim_name_portfolio.csv
Tabla de dimensiones "dim_name_product_type" guardada como dim_name_product_type.csv
Tabla de dimensiones "dim_channel_type" guardada como dim_channel_type.csv
Tabla de dimensiones "dim_name_seller_industry" guardada como dim_name_seller_industry.csv
Tabla de dimensiones "dim_name_yield_group" guardada como dim_name_yield_group.csv
Tabla de dimensiones "dim_product_combination" guardada como dim_product_combination.csv